-- ============================================================================
-- Dream And Do It – Kundenplattform
-- Etappe 13: Erweiterung Übungsbibliothek um Maschinen-/Kabelzug-/Kurzhantel-
-- Übungen für alle großen Muskelgruppen sowie gängige Cardio-Geräte.
--
-- Bewusst ohne image_url (Bildmaterial wird nachträglich ergänzt, siehe
-- content/uebungen/). Beschreibungsformat identisch zu den bestehenden 44
-- Übungen (Ausführung/Ausrüstung/Worauf achten, ohne Sätze/Wdh. — das gehört
-- fachlich erst zur konkreten Trainingsplan-Erstellung).
--
-- Im Supabase SQL Editor ausführen, NACHDEM 001-012 bereits liefen.
-- ============================================================================

insert into public.exercises (name, muscle_group, description, category, movement_pattern, image_url) values
('Brustpresse an der Maschine', 'Brust & Trizeps', 'Ausführung: Auf der Maschine sitzend die Griffe nach vorn drücken, bis die Arme fast gestreckt sind, dann kontrolliert zurückführen. Ausrüstung: Brustpresse-Maschine. Worauf achten: Rücken bleibt an der Lehne, Schultern nicht nach vorn ziehen, Bewegung ohne Schwung ausführen.', 'Kraft', 'push_oberkoerper', null),
('Kurzhantel-Bankdrücken (Flachbank)', 'Brust & Trizeps', 'Ausführung: Auf der Flachbank liegend die Kurzhanteln von Brusthöhe nach oben drücken, bis die Arme fast gestreckt sind, kontrolliert absenken. Ausrüstung: Kurzhanteln, Bank. Worauf achten: Schulterblätter zurückziehen und fixieren, Ellbogen ca. 45° zum Körper, gleichmäßige Bewegung beider Arme.', 'Kraft', 'push_oberkoerper', null),
('Kurzhantel-Fliegende (Flachbank)', 'Brust', 'Ausführung: Auf der Flachbank liegend die Kurzhanteln mit leicht gebeugten Ellbogen seitlich absenken, bis eine leichte Dehnung in der Brust spürbar ist, dann in einer großen Bogenbewegung wieder zusammenführen. Ausrüstung: Kurzhanteln, Bank. Worauf achten: Ellbogenwinkel während der gesamten Bewegung beibehalten, kontrolliert und ohne Schwung ausführen.', 'Kraft', 'push_oberkoerper', null),
('Butterfly an der Maschine', 'Brust', 'Ausführung: An der Butterfly-Maschine sitzend die Arme bzw. Polster vor dem Körper zusammenführen, kontrolliert wieder öffnen. Ausrüstung: Butterfly- bzw. Pec-Deck-Maschine. Worauf achten: Rücken an der Lehne, Bewegung aus der Brust einleiten, nicht in der Endposition einrasten lassen.', 'Kraft', 'push_oberkoerper', null),
('Kabelzug-Fliegende (Cable Crossover)', 'Brust', 'Ausführung: Am Kabelturm stehend beide Griffe von oben-außen in einer Bogenbewegung vor dem Körper zusammenführen. Ausrüstung: Kabelzug mit zwei hohen Umlenkrollen. Worauf achten: Leichte Vorbeuge und stabiler Stand, Bewegung kontrolliert und mit konstanter Spannung im Kabel ausführen.', 'Kraft', 'push_oberkoerper', null),
('Rudermaschine sitzend', 'Rücken & Bizeps', 'Ausführung: Sitzend am Rudergerät bzw. Kabelzug den Griff zum Bauch heranziehen, Schulterblätter dabei zusammenziehen, kontrolliert zurückführen. Ausrüstung: Rudermaschine oder Kabelzug mit V-Griff. Worauf achten: Oberkörper aufrecht und ruhig halten, Zug aus dem Rücken statt aus den Armen einleiten.', 'Kraft', 'pull_oberkoerper', null),
('Einarmiges Kurzhantelrudern', 'Rücken & Bizeps', 'Ausführung: Mit einem Knie und einer Hand auf der Bank abstützen, die Kurzhantel mit der anderen Hand seitlich am Körper nach oben ziehen. Ausrüstung: Kurzhantel, Bank. Worauf achten: Rücken gerade, Rumpf stabil, Ellbogen eng am Körper nach oben-hinten führen.', 'Kraft', 'pull_oberkoerper', null),
('Klimmzüge an der Assistenzmaschine', 'Rücken & Bizeps', 'Ausführung: Auf der Kniestütze der Assistenzmaschine den Körper am Griff nach oben ziehen, bis das Kinn etwa auf Stangenhöhe ist, kontrolliert absenken. Ausrüstung: Klimmzug-Assistenzmaschine. Worauf achten: Gewichtsunterstützung so wählen, dass die Bewegung sauber und ohne Schwung gelingt, Schultern aktiv nach unten ziehen.', 'Kraft', 'pull_oberkoerper', null),
('Rückenstrecker an der Maschine', 'Unterer Rücken & Gesäß', 'Ausführung: An der Rückenstrecker-Maschine den Oberkörper aus der Vorbeuge kontrolliert bis zur Streckung aufrichten, langsam wieder absenken. Ausrüstung: Rückenstrecker-Maschine. Worauf achten: Bewegung aus der Hüfte einleiten, keine Überstreckung im unteren Rücken, kontrolliertes Tempo.', 'Kraft', 'rumpf_hinten', null),
('Schulterpresse an der Maschine', 'Schultern & Trizeps', 'Ausführung: Sitzend an der Maschine die Griffe von Schulterhöhe nach oben drücken, kontrolliert absenken. Ausrüstung: Schulterpresse-Maschine. Worauf achten: Rücken an der Lehne, kein Hohlkreuz, Bewegung gleichmäßig und ohne Einrasten in der Endposition.', 'Kraft', 'push_oberkoerper', null),
('Seitheben mit Kurzhanteln', 'Schultern (seitlich)', 'Ausführung: Im Stand die Kurzhanteln seitlich bis auf Schulterhöhe anheben, kontrolliert absenken. Ausrüstung: Kurzhanteln. Worauf achten: Leichte Beugung im Ellbogen beibehalten, kein Schwung aus Beinen/Hüfte, Schultern unten lassen.', 'Kraft', 'push_oberkoerper', null),
('Frontheben mit Kurzhanteln', 'Schultern (vorne)', 'Ausführung: Im Stand die Kurzhanteln vor dem Körper bis auf Schulterhöhe anheben, kontrolliert absenken. Ausrüstung: Kurzhanteln. Worauf achten: Rumpf stabil, kein Schwung, Bewegung abwechselnd oder beidarmig kontrolliert ausführen.', 'Kraft', 'push_oberkoerper', null),
('Face Pulls am Kabelzug', 'Hintere Schulter & oberer Rücken', 'Ausführung: Am Kabelzug mit Seil auf Gesichtshöhe den Zug zum Gesicht heranziehen, Ellbogen dabei nach außen-oben führen, kontrolliert zurückführen. Ausrüstung: Kabelzug mit Seilgriff. Worauf achten: Schulterblätter zusammenziehen, Ellbogen bleiben auf Schulterhöhe, kein Zug aus dem unteren Rücken.', 'Kraft', 'pull_oberkoerper', null),
('Reverse Butterfly an der Maschine', 'Hintere Schulter & oberer Rücken', 'Ausführung: Rücklings an der Butterfly-Maschine sitzend die Arme seitlich nach hinten führen, Schulterblätter zusammenziehen, kontrolliert zurückführen. Ausrüstung: Butterfly-Maschine (Reverse-Position). Worauf achten: Bewegung aus dem oberen Rücken statt aus den Armen, aufrechte Sitzposition.', 'Kraft', 'pull_oberkoerper', null),
('Bizepscurls mit Kurzhanteln', 'Bizeps', 'Ausführung: Im Stand oder Sitzen die Kurzhanteln durch Beugen der Ellbogen nach oben führen, kontrolliert absenken. Ausrüstung: Kurzhanteln. Worauf achten: Ellbogen bleiben am Körper fixiert, kein Schwung aus dem Oberkörper.', 'Kraft', 'pull_oberkoerper', null),
('Hammercurls mit Kurzhanteln', 'Bizeps & Unterarm', 'Ausführung: Wie Bizepscurls, jedoch mit neutralem Griff (Handflächen zeigen zueinander) während der gesamten Bewegung. Ausrüstung: Kurzhanteln. Worauf achten: Handgelenke gerade halten, Ellbogen fixiert, kontrolliertes Tempo.', 'Kraft', 'pull_oberkoerper', null),
('Bizepscurls am Kabelzug', 'Bizeps', 'Ausführung: Am unteren Kabelzug mit Stange oder Seil die Ellbogen beugen und die Stange nach oben führen, kontrolliert absenken. Ausrüstung: Kabelzug mit Stangen- oder Seilgriff. Worauf achten: Oberkörper ruhig halten, Ellbogen am Körper fixiert, gleichmäßiger Zug ohne Schwung.', 'Kraft', 'pull_oberkoerper', null),
('Trizepsdrücken an der Maschine', 'Trizeps', 'Ausführung: An der Maschine sitzend die Griffe durch Strecken der Ellbogen nach unten bzw. vorn drücken, kontrolliert zurückführen. Ausrüstung: Trizepsdrücker-Maschine. Worauf achten: Oberarme bleiben ruhig, Bewegung ausschließlich im Ellbogengelenk.', 'Kraft', 'push_oberkoerper', null),
('Kurzhantel-Trizepsstrecken (über Kopf)', 'Trizeps', 'Ausführung: Sitzend oder stehend eine Kurzhantel mit beiden Händen über Kopf halten, Ellbogen beugen und die Hantel hinter den Kopf absenken, wieder strecken. Ausrüstung: Kurzhantel. Worauf achten: Ellbogen zeigen nach vorn und bleiben nah am Kopf, Rumpf stabil, kein Hohlkreuz.', 'Kraft', 'push_oberkoerper', null),
('Trizeps-Pushdown am Kabelzug', 'Trizeps', 'Ausführung: Am oberen Kabelzug mit Stange oder Seil die Ellbogen am Körper fixiert strecken, bis die Arme fast gerade sind, kontrolliert zurückführen. Ausrüstung: Kabelzug mit Stangen- oder Seilgriff. Worauf achten: Oberarme bleiben während der gesamten Bewegung am Oberkörper fixiert, kein Mitschwingen.', 'Kraft', 'push_oberkoerper', null),
('Beinpresse', 'Beine (Quadrizeps & Gesäß)', 'Ausführung: An der Beinpresse sitzend die Plattform durch Strecken der Beine nach oben bzw. vorn drücken, kontrolliert bis zum rechten Winkel im Knie absenken. Ausrüstung: Beinpresse. Worauf achten: Knie in Fußrichtung, unterer Rücken bleibt an der Lehne, Bewegung kontrolliert ohne Durchstoßen der Knie.', 'Kraft', 'vordere_beinkette', null),
('Beinstrecker an der Maschine', 'Beine (Quadrizeps)', 'Ausführung: Sitzend an der Maschine die Unterschenkel durch Strecken der Knie anheben, kontrolliert absenken. Ausrüstung: Beinstrecker-Maschine. Worauf achten: Rücken an der Lehne, Bewegung kontrolliert ohne Schwung, in der oberen Position kurz halten.', 'Kraft', 'vordere_beinkette', null),
('Beinbeuger an der Maschine', 'Beine (hintere Oberschenkelmuskulatur)', 'Ausführung: Liegend oder sitzend an der Maschine die Unterschenkel durch Beugen der Knie zum Gesäß heranziehen, kontrolliert zurückführen. Ausrüstung: Beinbeuger-Maschine (liegend oder sitzend). Worauf achten: Hüfte bleibt auf der Auflage, Bewegung kontrolliert ohne Schwung ausführen.', 'Kraft', 'hintere_beinkette', null),
('Wadenheben stehend an der Maschine', 'Waden', 'Ausführung: Stehend an der Maschine auf die Fußballen drücken, bis die Fersen maximal angehoben sind, kontrolliert absenken bis zur Dehnung. Ausrüstung: Wadenheben-Maschine (stehend). Worauf achten: Volle Bewegungsamplitude nutzen, Knie leicht gestreckt, kontrolliertes Tempo ohne Wippen.', 'Kraft', 'hintere_beinkette', null),
('Wadenheben sitzend an der Maschine', 'Waden', 'Ausführung: Sitzend an der Maschine mit Gewicht auf den Knien auf die Fußballen drücken, Fersen anheben, kontrolliert absenken. Ausrüstung: Wadenheben-Maschine (sitzend). Worauf achten: Volle Bewegungsamplitude, kontrolliertes Tempo, kein Wippen mit Schwung.', 'Kraft', 'hintere_beinkette', null),
('Adduktorenmaschine', 'Beine (Adduktoren, Innenseite)', 'Ausführung: Sitzend an der Maschine die Beine gegen den Widerstand zusammenführen, kontrolliert wieder öffnen. Ausrüstung: Adduktorenmaschine. Worauf achten: Rücken an der Lehne, Bewegung langsam und kontrolliert, kein Einrasten in der Endposition.', 'Kraft', 'sonstige', null),
('Abduktorenmaschine', 'Beine (Abduktoren, seitliches Gesäß)', 'Ausführung: Sitzend an der Maschine die Beine gegen den Widerstand nach außen drücken, kontrolliert wieder zusammenführen. Ausrüstung: Abduktorenmaschine. Worauf achten: Rücken an der Lehne, Bewegung langsam und kontrolliert ausführen.', 'Kraft', 'sonstige', null),
('Hüftstoßen mit der Langhantel (Hip Thrust)', 'Gesäß & hintere Oberschenkelmuskulatur', 'Ausführung: Mit dem oberen Rücken an einer Bank abgestützt und der Langhantel über der Hüfte die Hüfte nach oben strecken, bis Oberkörper und Oberschenkel eine Linie bilden, kontrolliert absenken. Ausrüstung: Langhantel (mit Polster), Bank. Worauf achten: Gesäß am oberen Punkt aktiv anspannen, kein Hohlkreuz, Kinn leicht zur Brust.', 'Kraft', 'hintere_beinkette', null),
('Kabelzug-Kickback', 'Gesäß', 'Ausführung: Mit einer Fußmanschette am unteren Kabelzug das gestreckte Bein nach hinten-oben führen, kontrolliert zurückführen. Ausrüstung: Kabelzug mit Fußmanschette. Worauf achten: Rumpf stabil, Bewegung aus dem Gesäß statt aus dem unteren Rücken, kein Schwung.', 'Kraft', 'hintere_beinkette', null),
('Kabel-Crunches (kniend)', 'Rumpf (gerade Bauchmuskulatur)', 'Ausführung: Kniend vor dem hohen Kabelzug mit Seilgriff den Oberkörper durch Anspannen der Bauchmuskulatur nach unten einrollen, kontrolliert zurückführen. Ausrüstung: Kabelzug mit Seilgriff. Worauf achten: Bewegung aus der Bauchmuskulatur, Hüfte bleibt weitgehend ruhig, kein Ziehen mit den Armen.', 'Kraft', 'rumpf_vorne', null),
('Beinheben hängend', 'Rumpf (untere Bauchmuskulatur) & Hüftbeuger', 'Ausführung: Hängend an der Klimmzugstange oder im Dip-/Klimmzugturm mit Armstütze die gestreckten oder angewinkelten Beine kontrolliert nach oben führen, langsam absenken. Ausrüstung: Klimmzugstange oder Dip-/Klimmzugturm mit Armstütze. Worauf achten: Schwungfrei arbeiten, Rumpf leicht einrollen statt nur die Hüfte zu beugen.', 'Kraft', 'rumpf_vorne', null),
('Laufband', 'Beine & Herz-Kreislauf-System', 'Ausführung: Gehen oder Laufen auf dem Laufband, Tempo und Steigung über die Konsole einstellen. Ausrüstung: Laufband. Worauf achten: Aufrechte Haltung, Blick nach vorn statt nach unten, Landung über den Mittelfuß, Intensität über Tempo/Steigung oder Herzfrequenz steuern.', 'Cardio', 'sonstige', null),
('Crosstrainer (Ellipsentrainer)', 'Ganzkörper & Herz-Kreislauf-System', 'Ausführung: Auf den Pedalen stehend die ellipsenförmige Bewegung mit aktivem Armeinsatz an den Griffen ausführen, Widerstand über die Konsole einstellen. Ausrüstung: Crosstrainer/Ellipsentrainer. Worauf achten: Aufrechte Haltung, gleichmäßiger Tritt, Gewicht nicht einseitig auf Fersen oder Fußballen verlagern.', 'Cardio', 'sonstige', null),
('Stepper', 'Beine, Gesäß & Herz-Kreislauf-System', 'Ausführung: Im gleichmäßigen Rhythmus auf die Pedale des Steppers treten, Widerstand/Tempo über die Konsole einstellen. Ausrüstung: Stepper. Worauf achten: Aufrechte Haltung, kein Abstützen mit vollem Körpergewicht auf den Griffen, Schritte kontrolliert statt mit Schwung.', 'Cardio', 'sonstige', null),
('Stairmaster (Treppensteiger)', 'Beine, Gesäß & Herz-Kreislauf-System', 'Ausführung: Kontinuierliches Treppensteigen auf dem Gerät, Tempo über die Konsole einstellen. Ausrüstung: Stairmaster/Treppensteiger. Worauf achten: Aufrechte Haltung, Fuß vollständig auf der Stufe aufsetzen, Griffe nur zur Balance statt zum Abstützen nutzen.', 'Cardio', 'sonstige', null),
('Liegerad (Recumbent Bike)', 'Beine & Herz-Kreislauf-System (gelenkschonend)', 'Ausführung: Im Sitzen mit Rückenlehne gleichmäßig in die Pedale treten, Widerstand über die Konsole einstellen. Ausrüstung: Liegerad/Recumbent Bike. Worauf achten: Sitzposition so einstellen, dass die Knie beim Treten nicht vollständig durchgestreckt werden, gleichmäßige Trittfrequenz.', 'Cardio', 'sonstige', null),
('Fahrrad-Ergometer', 'Beine & Herz-Kreislauf-System', 'Ausführung: Im Sitzen gleichmäßig in die Pedale treten, Widerstand/Watt über die Konsole einstellen. Ausrüstung: Fahrrad-Ergometer. Worauf achten: Sattelhöhe so einstellen, dass die Knie im unteren Punkt leicht gebeugt bleiben, aufrechter Oberkörper, gleichmäßige Trittfrequenz.', 'Cardio', 'sonstige', null);
