-- ============================================================================
-- Dream And Do It – Kundenplattform
-- Etappe 13: Erweiterung Übungsbibliothek um Maschinen-/Kabelzug-/Kurzhantel-
-- Übungen für alle großen Muskelgruppen sowie gängige Cardio-Geräte.
--
-- Bewusst ohne image_url (Bildmaterial wird nachträglich ergänzt, siehe
-- content/uebungen/). Beschreibungsformat identisch zu den bestehenden 44
-- Übungen (Ausführung/Ausrüstung/Worauf achten, ohne Sätze/Wdh. — das gehört
-- fachlich erst zur konkreten Trainingsplan-Erstellung).
--
-- Im Supabase SQL Editor ausführen, NACHDEM 001-012 bereits liefen.
-- ============================================================================

insert into public.exercises (name, muscle_group, description, category, movement_pattern, image_url) values
('Brustpresse an der Maschine', 'Brust & Trizeps', 'Ausführung: Sitzhöhe so einstellen, dass die Griffe auf Brusthöhe liegen, dann auf der Maschine sitzend die Griffe nach vorn drücken, bis die Arme fast gestreckt sind, dann kontrolliert bis zur leichten Dehnung in der Brust zurückführen. Ausrüstung: Brustpresse-Maschine. Worauf achten: Rücken und Kopf bleiben durchgehend an der Lehne, Schultern nicht nach vorn ziehen oder hochziehen, Ellbogen nicht komplett durchdrücken, Bewegung ohne Schwung ausführen.', 'Kraft', 'push_oberkoerper', null),
('Kurzhantel-Bankdrücken (Flachbank)', 'Brust & Trizeps', 'Ausführung: Auf der Flachbank liegend mit festem Fußkontakt zum Boden die Kurzhanteln von Brusthöhe nach oben drücken, bis die Arme fast gestreckt sind, dann kontrolliert bis auf Brusthöhe absenken. Ausrüstung: Kurzhanteln, Bank. Worauf achten: Schulterblätter zurückziehen und während der gesamten Bewegung fixieren, Ellbogen ca. 45° zum Körper, gleichmäßige Bewegung beider Arme, Hanteln beim Absenken nicht unkontrolliert nach außen kippen lassen.', 'Kraft', 'push_oberkoerper', null),
('Kurzhantel-Fliegende (Flachbank)', 'Brust', 'Ausführung: Auf der Flachbank liegend die Kurzhanteln über der Brust mit leicht gebeugten Ellbogen halten, dann seitlich in einer Bogenbewegung absenken, bis eine leichte Dehnung in der Brust spürbar ist, dann in derselben Bogenbewegung wieder zusammenführen. Ausrüstung: Kurzhanteln, Bank. Worauf achten: Ellbogenwinkel während der gesamten Bewegung beibehalten, nicht tiefer absenken als schulterschonend möglich, kontrolliert und ohne Schwung ausführen, moderates Gewicht wählen, da die Schulter in der Dehnungsposition wenig Schutz hat.', 'Kraft', 'push_oberkoerper', null),
('Butterfly an der Maschine', 'Brust', 'Ausführung: An der Butterfly-Maschine mit an der Lehne anliegendem Rücken sitzen, die Arme bzw. Polster vor dem Körper kontrolliert zusammenführen, dann bis zur leichten Dehnung in der Brust wieder öffnen. Ausrüstung: Butterfly- bzw. Pec-Deck-Maschine. Worauf achten: Rücken durchgehend an der Lehne, Bewegung aus der Brust einleiten statt aus den Schultern, nicht in der Endposition einrasten lassen, Arme nicht weiter öffnen als schulterschonend möglich.', 'Kraft', 'push_oberkoerper', null),
('Kabelzug-Fliegende (Cable Crossover)', 'Brust', 'Ausführung: Am Kabelturm mit einem Bein leicht nach vorn versetzt stehen, beide Griffe von oben-außen mit leicht gebeugten Ellbogen in einer Bogenbewegung vor dem Körper zusammenführen, dann kontrolliert zurück bis zur leichten Dehnung in der Brust führen. Ausrüstung: Kabelzug mit zwei hohen Umlenkrollen. Worauf achten: Leichte Vorbeuge und stabiler Stand, Ellbogenwinkel beibehalten, Bewegung kontrolliert und mit konstanter Spannung im Kabel ausführen, nicht zu weit zurückführen, um die Schulter zu schonen.', 'Kraft', 'push_oberkoerper', null),
('Rudermaschine sitzend', 'Rücken & Bizeps', 'Ausführung: Sitzend mit leicht gebeugten Knien und aufgerichtetem Oberkörper am Rudergerät bzw. Kabelzug den Griff zum Bauch heranziehen, Schulterblätter dabei zusammenziehen, kontrolliert bis zur fast vollen Armstreckung zurückführen. Ausrüstung: Rudermaschine oder Kabelzug mit V-Griff. Worauf achten: Oberkörper aufrecht und ruhig halten, kein Vor- und Zurückschaukeln, Zug aus dem Rücken statt aus den Armen einleiten, Ellbogen eng am Körper führen.', 'Kraft', 'pull_oberkoerper', null),
('Einarmiges Kurzhantelrudern', 'Rücken & Bizeps', 'Ausführung: Mit einem Knie und der gleichseitigen Hand auf der Bank abstützen, Rücken gerade und parallel zum Boden ausrichten, die Kurzhantel mit der anderen Hand seitlich am Körper nach oben-hinten ziehen, kontrolliert bis zur vollen Armstreckung absenken. Ausrüstung: Kurzhantel, Bank. Worauf achten: Rücken gerade, Rumpf stabil, keine Rotation im Oberkörper, Ellbogen eng am Körper nach oben-hinten führen.', 'Kraft', 'pull_oberkoerper', null),
('Klimmzüge an der Assistenzmaschine', 'Rücken & Bizeps', 'Ausführung: Auf der Kniestütze der Assistenzmaschine mit schulterbreitem Griff den Körper durch Zug der Rückenmuskulatur nach oben ziehen, bis das Kinn etwa auf Stangenhöhe ist, kontrolliert bis zur fast vollen Armstreckung absenken. Ausrüstung: Klimmzug-Assistenzmaschine. Worauf achten: Gewichtsunterstützung so wählen, dass die Bewegung sauber und ohne Schwung gelingt, Schultern aktiv nach unten ziehen, Rumpf während der Bewegung stabil halten.', 'Kraft', 'pull_oberkoerper', null),
('Rückenstrecker an der Maschine', 'Unterer Rücken & Gesäß', 'Ausführung: An der Rückenstrecker-Maschine mit an der Polsterung fixierter Hüfte den Oberkörper aus der Vorbeuge kontrolliert bis zur neutralen Wirbelsäulenstellung aufrichten, langsam wieder absenken. Ausrüstung: Rückenstrecker-Maschine. Worauf achten: Bewegung aus der Hüfte einleiten, keine Überstreckung ins Hohlkreuz am oberen Punkt, kontrolliertes Tempo ohne Schwung, bei Rückenbeschwerden die Bewegungsamplitude reduzieren.', 'Kraft', 'rumpf_hinten', null),
('Schulterpresse an der Maschine', 'Schultern & Trizeps', 'Ausführung: Sitzend mit dem Rücken an der Lehne die Griffe von Schulterhöhe nach oben drücken, bis die Arme fast gestreckt sind, kontrolliert wieder bis auf Schulterhöhe absenken. Ausrüstung: Schulterpresse-Maschine. Worauf achten: Rücken durchgehend an der Lehne, kein Hohlkreuz im unteren Rücken, Bewegung gleichmäßig und ohne Einrasten in der Endposition, Handgelenke gerade über den Ellbogen halten.', 'Kraft', 'push_oberkoerper', null),
('Seitheben mit Kurzhanteln', 'Schultern (seitlich)', 'Ausführung: Im hüftbreiten Stand mit leicht gebeugten Knien die Kurzhanteln seitlich bis auf Schulterhöhe anheben, kontrolliert absenken. Ausrüstung: Kurzhanteln. Worauf achten: Leichte Beugung im Ellbogen beibehalten, kein Schwung aus Beinen/Hüfte, Schultern unten lassen statt hochzuziehen, nicht über Schulterhöhe anheben.', 'Kraft', 'push_oberkoerper', null),
('Frontheben mit Kurzhanteln', 'Schultern (vorne)', 'Ausführung: Im hüftbreiten Stand die Kurzhanteln vor dem Körper mit leicht gebeugten Ellbogen bis auf Schulterhöhe anheben, kontrolliert absenken. Ausrüstung: Kurzhanteln. Worauf achten: Rumpf stabil, kein Schwung aus dem unteren Rücken, Bewegung abwechselnd oder beidarmig kontrolliert ausführen, Schultern unten lassen.', 'Kraft', 'push_oberkoerper', null),
('Face Pulls am Kabelzug', 'Hintere Schulter & oberer Rücken', 'Ausführung: Am Kabelzug mit Seilgriff auf Gesichtshöhe den Zug bei aufrechtem Oberkörper zum Gesicht heranziehen, Ellbogen dabei nach außen-oben führen, kontrolliert bis zur fast vollen Armstreckung zurückführen. Ausrüstung: Kabelzug mit Seilgriff. Worauf achten: Schulterblätter aktiv zusammenziehen, Ellbogen bleiben auf Schulterhöhe, kein Zug aus dem unteren Rücken, leichtes bis moderates Gewicht für saubere Technik wählen.', 'Kraft', 'pull_oberkoerper', null),
('Reverse Butterfly an der Maschine', 'Hintere Schulter & oberer Rücken', 'Ausführung: Rücklings an der Butterfly-Maschine mit Brustkontakt zur Polsterung sitzend die Arme seitlich mit leicht gebeugten Ellbogen nach hinten führen, Schulterblätter zusammenziehen, kontrolliert zurückführen. Ausrüstung: Butterfly-Maschine (Reverse-Position). Worauf achten: Bewegung aus dem oberen Rücken statt aus den Armen einleiten, aufrechte Sitzposition, kein Hochziehen der Schultern.', 'Kraft', 'pull_oberkoerper', null),
('Bizepscurls mit Kurzhanteln', 'Bizeps', 'Ausführung: Im Stand oder Sitzen mit herabhängenden Armen die Kurzhanteln durch Beugen der Ellbogen nach oben führen, bis die Unterarme senkrecht stehen, kontrolliert bis zur fast vollen Streckung absenken. Ausrüstung: Kurzhanteln. Worauf achten: Ellbogen bleiben während der gesamten Bewegung am Körper fixiert, kein Schwung aus dem Oberkörper oder den Schultern.', 'Kraft', 'pull_oberkoerper', null),
('Hammercurls mit Kurzhanteln', 'Bizeps & Unterarm', 'Ausführung: Wie Bizepscurls, jedoch mit neutralem Griff (Handflächen zeigen zueinander) während der gesamten Auf- und Abwärtsbewegung ausführen. Ausrüstung: Kurzhanteln. Worauf achten: Handgelenke gerade halten, Ellbogen am Körper fixiert, kontrolliertes Tempo ohne Schwung aus dem Oberkörper.', 'Kraft', 'pull_oberkoerper', null),
('Bizepscurls am Kabelzug', 'Bizeps', 'Ausführung: Am unteren Kabelzug mit aufrechtem Stand die Ellbogen beugen und die Stange oder das Seil nach oben führen, kontrolliert bis zur fast vollen Armstreckung absenken. Ausrüstung: Kabelzug mit Stangen- oder Seilgriff. Worauf achten: Oberkörper ruhig halten, Ellbogen am Körper fixiert, gleichmäßiger Zug ohne Schwung aus Hüfte oder Rücken.', 'Kraft', 'pull_oberkoerper', null),
('Trizepsdrücken an der Maschine', 'Trizeps', 'Ausführung: An der Maschine sitzend mit Oberarmen nah am Körper die Griffe durch Strecken der Ellbogen nach unten bzw. vorn drücken, kontrolliert bis zur Ausgangsposition zurückführen. Ausrüstung: Trizepsdrücker-Maschine. Worauf achten: Oberarme bleiben während der gesamten Bewegung ruhig und am Körper, Bewegung ausschließlich im Ellbogengelenk, Ellbogen nicht mit Schwung durchdrücken.', 'Kraft', 'push_oberkoerper', null),
('Kurzhantel-Trizepsstrecken (über Kopf)', 'Trizeps', 'Ausführung: Sitzend oder stehend eine Kurzhantel mit beiden Händen über Kopf halten, Ellbogen kontrolliert beugen und die Hantel hinter den Kopf bis zur leichten Dehnung im Trizeps absenken, dann wieder strecken. Ausrüstung: Kurzhantel. Worauf achten: Ellbogen zeigen nach vorn und bleiben während der gesamten Bewegung nah am Kopf, Rumpf stabil, kein Hohlkreuz, moderates Gewicht wählen, da die Ellbogen in dieser Position stärker belastet werden.', 'Kraft', 'push_oberkoerper', null),
('Trizeps-Pushdown am Kabelzug', 'Trizeps', 'Ausführung: Am oberen Kabelzug mit leicht vorgebeugtem Oberkörper die Ellbogen am Körper fixiert strecken, bis die Arme fast gerade sind, kontrolliert bis zum rechten Winkel im Ellbogen zurückführen. Ausrüstung: Kabelzug mit Stangen- oder Seilgriff. Worauf achten: Oberarme bleiben während der gesamten Bewegung am Oberkörper fixiert, kein Mitschwingen aus Schulter oder Rumpf, Handgelenke gerade halten.', 'Kraft', 'push_oberkoerper', null),
('Beinpresse', 'Beine (Quadrizeps & Gesäß)', 'Ausführung: An der Beinpresse mit hüftbreit auf der Plattform platzierten Füßen die Plattform durch Strecken der Beine nach oben bzw. vorn drücken, kontrolliert bis zum rechten Winkel im Knie absenken. Ausrüstung: Beinpresse. Worauf achten: Knie in Fußrichtung, unterer Rücken bleibt durchgehend an der Lehne, Bewegung kontrolliert ohne Durchstoßen der Knie am oberen Punkt, Gesäß nicht von der Sitzfläche abheben.', 'Kraft', 'vordere_beinkette', null),
('Beinstrecker an der Maschine', 'Beine (Quadrizeps)', 'Ausführung: Sitzend mit dem Rücken an der Lehne und den Polstern auf den Schienbeinen die Unterschenkel durch Strecken der Knie anheben, in der oberen Position kurz halten, kontrolliert absenken. Ausrüstung: Beinstrecker-Maschine. Worauf achten: Rücken durchgehend an der Lehne, Bewegung kontrolliert ohne Schwung, Knie am oberen Punkt nicht ruckartig durchdrücken.', 'Kraft', 'vordere_beinkette', null),
('Beinbeuger an der Maschine', 'Beine (hintere Oberschenkelmuskulatur)', 'Ausführung: Liegend oder sitzend an der Maschine mit den Polstern an den Fersen die Unterschenkel durch Beugen der Knie zum Gesäß heranziehen, kontrolliert bis zur fast vollen Streckung zurückführen. Ausrüstung: Beinbeuger-Maschine (liegend oder sitzend). Worauf achten: Hüfte bleibt durchgehend auf der Auflage, Bewegung kontrolliert ohne Schwung ausführen, kein Hohlkreuz durch Abheben des Beckens.', 'Kraft', 'hintere_beinkette', null),
('Wadenheben stehend an der Maschine', 'Waden', 'Ausführung: Stehend an der Maschine mit den Fußballen auf der Stufe auf die Fußballen drücken, bis die Fersen maximal angehoben sind, kontrolliert bis zur deutlichen Dehnung in der Wade absenken. Ausrüstung: Wadenheben-Maschine (stehend). Worauf achten: Volle Bewegungsamplitude nutzen, Knie leicht gestreckt, kontrolliertes Tempo ohne Wippen oder Abfedern am unteren Punkt.', 'Kraft', 'hintere_beinkette', null),
('Wadenheben sitzend an der Maschine', 'Waden', 'Ausführung: Sitzend an der Maschine mit den Polstern auf den Knien und den Fußballen auf der Stufe auf die Fußballen drücken, Fersen maximal anheben, kontrolliert bis zur Dehnung absenken. Ausrüstung: Wadenheben-Maschine (sitzend). Worauf achten: Volle Bewegungsamplitude, kontrolliertes Tempo, kein Wippen mit Schwung, Gewicht moderat wählen, um die Knie nicht zu überlasten.', 'Kraft', 'hintere_beinkette', null),
('Adduktorenmaschine', 'Beine (Adduktoren, Innenseite)', 'Ausführung: Sitzend an der Maschine mit den Außenseiten der Knie an den Polstern die Beine gegen den Widerstand zusammenführen, kontrolliert bis zur angenehmen Dehnung wieder öffnen. Ausrüstung: Adduktorenmaschine. Worauf achten: Rücken an der Lehne, Bewegung langsam und kontrolliert, kein Einrasten in der Endposition, Öffnungsweite nicht bis in den schmerzhaften Bereich steigern.', 'Kraft', 'sonstige', null),
('Abduktorenmaschine', 'Beine (Abduktoren, seitliches Gesäß)', 'Ausführung: Sitzend an der Maschine mit den Außenseiten der Knie an den Polstern die Beine gegen den Widerstand nach außen drücken, kontrolliert wieder zusammenführen. Ausrüstung: Abduktorenmaschine. Worauf achten: Rücken an der Lehne, Bewegung langsam und kontrolliert ausführen, Oberkörper dabei ruhig halten statt mitzuschwingen.', 'Kraft', 'sonstige', null),
('Hüftstoßen mit der Langhantel (Hip Thrust)', 'Gesäß & hintere Oberschenkelmuskulatur', 'Ausführung: Mit dem oberen Rücken an einer Bank abgestützt, Füße hüftbreit nah am Gesäß aufgestellt und der Langhantel mit Polster über der Hüfte die Hüfte kraftvoll nach oben strecken, bis Oberkörper und Oberschenkel eine Linie bilden, kontrolliert absenken. Ausrüstung: Langhantel (mit Polster), Bank. Worauf achten: Gesäß am oberen Punkt aktiv anspannen, kein Hohlkreuz, Kinn leicht zur Brust, Knie zeigen während der Bewegung in Fußrichtung.', 'Kraft', 'hintere_beinkette', null),
('Kabelzug-Kickback', 'Gesäß', 'Ausführung: Mit einer Fußmanschette am unteren Kabelzug und leicht nach vorn geneigtem Oberkörper das gestreckte Bein kontrolliert nach hinten-oben führen, kontrolliert zurückführen. Ausrüstung: Kabelzug mit Fußmanschette. Worauf achten: Rumpf stabil, Bewegung aus dem Gesäß statt aus dem unteren Rücken, kein Schwung, Standbein leicht gebeugt für sicheren Halt.', 'Kraft', 'hintere_beinkette', null),
('Kabel-Crunches (kniend)', 'Rumpf (gerade Bauchmuskulatur)', 'Ausführung: Kniend vor dem hohen Kabelzug mit Seilgriff neben dem Kopf den Oberkörper durch Anspannen der Bauchmuskulatur nach unten Richtung Oberschenkel einrollen, kontrolliert zurückführen. Ausrüstung: Kabelzug mit Seilgriff. Worauf achten: Bewegung aus der Bauchmuskulatur einleiten, Hüfte bleibt weitgehend ruhig, kein Ziehen mit den Armen, Nacken entspannt lassen.', 'Kraft', 'rumpf_vorne', null),
('Beinheben hängend', 'Rumpf (untere Bauchmuskulatur) & Hüftbeuger', 'Ausführung: Hängend an der Klimmzugstange oder im Dip-/Klimmzugturm mit Armstütze und stabilisiertem Oberkörper die gestreckten oder angewinkelten Beine kontrolliert nach oben führen, langsam bis zur fast vollen Streckung absenken. Ausrüstung: Klimmzugstange oder Dip-/Klimmzugturm mit Armstütze. Worauf achten: Schwungfrei arbeiten, Rumpf leicht einrollen statt nur die Hüfte zu beugen, bei Anfängern mit angewinkelten Beinen beginnen.', 'Kraft', 'rumpf_vorne', null),
('Laufband', 'Beine & Herz-Kreislauf-System', 'Ausführung: Gehen oder Laufen auf dem Laufband, Tempo und Steigung schrittweise über die Konsole einstellen und erst starten, wenn ein sicherer Stand gefunden ist. Ausrüstung: Laufband. Worauf achten: Aufrechte Haltung, Blick nach vorn statt nach unten, Landung über den Mittelfuß, Notausschalter/Sicherheitsclip nutzen, Intensität über Tempo/Steigung oder Herzfrequenz steuern.', 'Cardio', 'sonstige', null),
('Crosstrainer (Ellipsentrainer)', 'Ganzkörper & Herz-Kreislauf-System', 'Ausführung: Auf den Pedalen mit aufrechtem Oberkörper stehend die ellipsenförmige Bewegung mit aktivem Armeinsatz an den Griffen ausführen, Widerstand schrittweise über die Konsole einstellen. Ausrüstung: Crosstrainer/Ellipsentrainer. Worauf achten: Aufrechte Haltung, gleichmäßiger Tritt, Gewicht nicht einseitig auf Fersen oder Fußballen verlagern, Knie in Fußrichtung führen.', 'Cardio', 'sonstige', null),
('Stepper', 'Beine, Gesäß & Herz-Kreislauf-System', 'Ausführung: Im gleichmäßigen Rhythmus mit aufrechter Haltung auf die Pedale des Steppers treten, Widerstand/Tempo schrittweise über die Konsole einstellen. Ausrüstung: Stepper. Worauf achten: Aufrechte Haltung, kein Abstützen mit vollem Körpergewicht auf den Griffen, Schritte kontrolliert statt mit Schwung, Fuß vollständig auf dem Pedal aufsetzen.', 'Cardio', 'sonstige', null),
('Stairmaster (Treppensteiger)', 'Beine, Gesäß & Herz-Kreislauf-System', 'Ausführung: Kontinuierliches Treppensteigen auf dem Gerät mit aufrechtem Oberkörper, Tempo schrittweise über die Konsole einstellen. Ausrüstung: Stairmaster/Treppensteiger. Worauf achten: Aufrechte Haltung, Fuß vollständig auf der Stufe aufsetzen, Griffe nur zur Balance statt zum Abstützen nutzen, nicht auf die Zehenspitzen verlagern.', 'Cardio', 'sonstige', null),
('Liegerad (Recumbent Bike)', 'Beine & Herz-Kreislauf-System (gelenkschonend)', 'Ausführung: Im Sitzen mit Rückenlehne die Sitzposition vor dem Start passend einstellen und gleichmäßig in die Pedale treten, Widerstand schrittweise über die Konsole einstellen. Ausrüstung: Liegerad/Recumbent Bike. Worauf achten: Sitzposition so einstellen, dass die Knie beim Treten nicht vollständig durchgestreckt werden, gleichmäßige Trittfrequenz, Rücken flächig an der Lehne.', 'Cardio', 'sonstige', null),
('Fahrrad-Ergometer', 'Beine & Herz-Kreislauf-System', 'Ausführung: Im Sitzen mit korrekt eingestellter Sattelhöhe gleichmäßig in die Pedale treten, Widerstand/Watt schrittweise über die Konsole einstellen. Ausrüstung: Fahrrad-Ergometer. Worauf achten: Sattelhöhe so einstellen, dass die Knie im unteren Punkt leicht gebeugt bleiben, aufrechter Oberkörper, gleichmäßige Trittfrequenz, Knie beim Treten in Fußrichtung führen.', 'Cardio', 'sonstige', null);
