-- ============================================================================
-- Dream And Do It – Kundenplattform
-- Runde 18 (Nachtrag): Übungsbeschreibungen tatsächlich in die Datenbank
-- übernehmen.
--
-- Hintergrund: In Runde 18 wurden alle 204 Übungsbeschreibungen inhaltlich
-- überarbeitet (keine Sätze-/Wiederholungs-/Gewichts-/RPE-Angaben mehr,
-- dafür mehr Sicherheits-/Ausführungsdetail). Diese Überarbeitung wurde
-- jedoch fälschlich nur in den ORIGINAL-Migrationsdateien (sql/006, sql/008,
-- sql/013, sql/026, sql/034) selbst geändert – diese Dateien waren zu dem
-- Zeitpunkt aber längst ausgeführt und wirken sich auf eine bereits
-- befüllte Datenbank nicht mehr aus. Ergebnis: die neuen Beschreibungen
-- lagen nur im ausgelieferten Code, nicht in der echten Datenbank – daher
-- waren in der Kundenplattform weiterhin die alten Beschreibungen (inkl.
-- Sätze/Wiederholungen) sichtbar.
--
-- Dieses Skript holt das nach: eine echte UPDATE-Anweisung je Übung mit dem
-- bereits überarbeiteten Text, für alle 204 Übungen. Keine Auswirkung auf
-- name/muscle_group/category/movement_pattern/image_url.
--
-- Im Supabase SQL Editor ausführen (nach 001–046 bereits gelaufen).
-- ============================================================================

update public.exercises set description = 'Ausführung: Im tiefen Ausfallschritt mit aufrechtem Oberkörper stehen, den Oberkörper kontrolliert zur vorderen Seite rotieren, Arme dabei großzügig kreisen lassen. Ausrüstung: keine. Worauf achten: Bewegung aktiv durch den vollen Bewegungsradius führen, nicht schwungvoll "durchschlagen", vorderes Knie bleibt über dem Fuß.' where name = 'Armkreisen mit Ausfallschritt & Rotation';
update public.exercises set description = 'Ausführung: Im hüftbreiten Stand die Hüfte großzügig und langsam kreisen, anschließend das Bein locker nach vorn/hinten sowie seitlich pendeln lassen. Ausrüstung: keine, ggf. Festhalten an einer Wand zur Balance. Worauf achten: Kontrolliert und im schmerzfreien Bewegungsraum bleiben, Oberkörper dabei ruhig und aufrecht halten.' where name = 'Hüftkreisen & Beinpendel';
update public.exercises set description = 'Ausführung: Im Vierfüßlerstand mit Händen unter den Schultern und Knien unter der Hüfte abwechselnd den Rücken rund machen (Kuh) und sanft ins Hohlkreuz gehen (Katze). Ausrüstung: Matte. Worauf achten: Bewegung langsam und mit der Atmung koordinieren (Ausatmen beim Runden, Einatmen beim Strecken), nur im schmerzfreien Bereich bewegen.' where name = 'Katze-Kuh-Mobilisation';
update public.exercises set description = 'Ausführung: In Rückenlage mit aufgestellten Füßen hüftbreit die Hüfte kontrolliert anheben, bis Schultern-Hüfte-Knie eine Linie bilden, kurz halten, kontrolliert absenken. Ausrüstung: Matte. Worauf achten: Gesäß aktiv anspannen, kein Hohlkreuz im unteren Rücken, Knie fallen nicht nach außen oder innen.' where name = 'Hip Bridge';
update public.exercises set description = 'Ausführung: Im Vierfüßlerstand mit angespanntem Rumpf gegenüberliegenden Arm und Bein gleichzeitig strecken, kurz halten, kontrolliert zurückführen, Seite wechseln. Ausrüstung: Matte. Worauf achten: Becken bleibt ruhig und gerade, keine Ausweichbewegung im Rumpf, Bewegung langsam statt mit Schwung ausführen.' where name = 'Bird Dog';
update public.exercises set description = 'Ausführung: Lockeres Skipping (kurze, schnelle Schritte) im Wechsel mit Kniehebelauf auf der Stelle oder über kurze Distanz ausführen. Ausrüstung: keine. Worauf achten: Aufrechte Körperhaltung, aktiver Armeinsatz, weiche Landung über den Fußballen.' where name = 'Skipping & Kniehebelauf';
update public.exercises set description = 'Ausführung: Im Sprung die Beine seitlich öffnen und die Arme über Kopf führen, im nächsten Sprung zurück in die Ausgangsposition. Ausrüstung: keine. Worauf achten: Weiche Landung über den Fußballen, gleichmäßiger Rhythmus, Knie beim Landen leicht gebeugt.' where name = 'Jumping Jacks';
update public.exercises set description = 'Ausführung: Im Stand oder Kniestand mit angespanntem Rumpf den Medizinball kontrolliert seitlich am Körper vorbeiführen, Blick folgt dem Ball. Ausrüstung: Medizinball oder Gymnastikball. Worauf achten: Core-Spannung durchgehend halten, Rotation kontrolliert statt mit Schwung ausführen, Wirbelsäule stabil und aufrecht.' where name = 'BWS-Rotation mit Medizinball';
update public.exercises set description = 'Ausführung: Aus dem Ausfallschritt heraus mit Gewicht in den Händen explosiv nach oben/vorn abdrücken, weich landen. Ausrüstung: Kurzhantel oder Kettlebell. Worauf achten: Explosiver Antritt, Rumpf fest, weiche Landung über den Fußballen, Knie fällt beim Landen nicht nach innen.' where name = 'Ausfallschritt mit explosivem Ausstoßen';
update public.exercises set description = 'Ausführung: Einbeinig auf Balance-Pad oder Matte stehen, Oberkörper kontrolliert nach vorn absenken, Standbein leicht gebeugt, Seite wechseln. Ausrüstung: Balance-Pad oder Matte. Worauf achten: Blick nach unten-vorn, Rumpf und Gesäß fest, Oberkörper und Spielbein bilden eine gerade Linie, bei Wackeln die Bewegungsamplitude reduzieren.' where name = 'Standwaage auf instabiler Unterlage';
update public.exercises set description = 'Ausführung: Langhantel mit geradem Rücken und hüftbreitem Stand vom Boden aufnehmen, Hüfte und Knie strecken sich gleichzeitig. Ausrüstung: Langhantel. Worauf achten: Rücken lang und gerade, Rumpf fest, Stange nah am Körper führen, Schultern über der Stange starten.' where name = 'Kreuzheben';
update public.exercises set description = 'Ausführung: Langhantel im schulterbreiten Griff eng am Körper bis auf Brusthöhe hochziehen, kontrolliert absenken. Ausrüstung: Langhantel. Worauf achten: Rumpf fest, Ellbogen führen die Bewegung nach außen/oben, nicht über Schulterhöhe ziehen, um die Schulter zu schonen.' where name = 'Aufrechtes Rudern (Langhantel)';
update public.exercises set description = 'Ausführung: Auf einem rutschigen Tuch oder Slider mit dem freien Bein seitlich in den Ausfallschritt gleiten und wieder zurückziehen. Ausrüstung: Slider oder glattes Tuch. Worauf achten: Rumpf fest, kontrolliert gleiten statt abrupt, über die Ferse des Standbeins abdrücken.' where name = 'Seitliches Gleiten im Ausfallschritt';
update public.exercises set description = 'Ausführung: Sitzend mit fixierten Oberschenkeln die Stange am Latzug-Gerät zur oberen Brust herunterziehen, kontrolliert zurückführen. Ausrüstung: Latzug-Gerät. Worauf achten: Oberkörper leicht nach hinten geneigt, Rumpf fest, Ellbogen nach unten/hinten führen, Stange nicht hinter den Nacken ziehen.' where name = 'Latzug frontal';
update public.exercises set description = 'Ausführung: Im Unterarm-Seitstütz mit Ellbogen unter der Schulter das obere Knie kontrolliert zur Brust ziehen und wieder strecken. Ausrüstung: keine. Worauf achten: Gerade Linie halten, Hüfte stabil und nicht absinken lassen, Knie aktiv zur Brust führen.' where name = 'Seitstütz mit Hüftbeuger-Anzug';
update public.exercises set description = 'Ausführung: Am Kabelzug mit hüftbreitem Stand den Zug unter kontrollierter Rumpfrotation von einer Seite zur anderen führen. Ausrüstung: Kabelzug. Worauf achten: Becken stabil halten, Rotation bewusst aus Brust- und Bauchmuskulatur einleiten statt aus den Armen zu ziehen.' where name = 'Wirbelsäulen-Rotation am Seilzug';
update public.exercises set description = 'Ausführung: Aus dem Stand einen großen Schritt zur Seite setzen, Gewicht auf das gebeugte Bein verlagern, dann über die Ferse zurückdrücken. Ausrüstung: keine oder Slider. Worauf achten: Rumpf fest, kontrollierte Bewegung, Knie des gebeugten Beins bleibt über dem Fuß.' where name = 'Seitlicher Ausfallschritt (stehend)';
update public.exercises set description = 'Ausführung: Langhantel im Nacken oder auf den Schultern halten, in die Hocke gehen, bis die Oberschenkel etwa parallel zum Boden sind, dann über die Fersen wieder aufstehen. Ausrüstung: Langhantel. Worauf achten: Blick nach vorn-unten, Rumpf fest, Knie in Fußrichtung und fallen nicht nach innen.' where name = 'Kniebeuge (Langhantel)';
update public.exercises set description = 'Ausführung: Auf instabiler Unterlage stehend die Brustwirbelsäule kontrolliert überstrecken, dann die Ellbogen eng am Körper zurückziehen. Ausrüstung: Balance-Pad, Kabelzug oder Expander. Worauf achten: Balance während der gesamten Bewegung halten, bei Unsicherheit zunächst auf festem Untergrund üben.' where name = 'BWS-Extension mit Ruderzug (instabil)';
update public.exercises set description = 'Ausführung: Langhantel von Schulterhöhe mit angespanntem Rumpf kontrolliert über Kopf drücken, bis die Arme fast gestreckt sind, dann absenken. Ausrüstung: Langhantel. Worauf achten: Rumpf und Gesäß fest, kein Hohlkreuz im unteren Rücken, Kopf leicht nach vorn aus der Bahn der Stange nehmen.' where name = 'Schulterdrücken (Langhantel, stehend)';
update public.exercises set description = 'Ausführung: Den hinteren Fuß erhöht auf einer Bank ablegen und mit dem vorderen Bein kontrolliert in die Kniebeuge gehen, dann über die vordere Ferse aufstehen. Ausrüstung: Langhantel, Bank. Worauf achten: Oberkörper aufrecht, Blick geradeaus, vorderes Knie bleibt über dem Fuß, kontrollierte Tiefe.' where name = 'Bulgarian Split Squat (Langhantel)';
update public.exercises set description = 'Ausführung: Auf Unterarmen (Ellbogen unter den Schultern) und Zehenspitzen abstützen, Körper bildet eine gerade Linie, Position ruhig halten. Ausrüstung: keine. Worauf achten: Gerade Linie von Schulter bis Ferse, kein Hohlkreuz oder Durchhängen im Becken, gleichmäßig weiteratmen.' where name = 'Unterarmstütz (Plank)';
update public.exercises set description = 'Ausführung: Unterarme auf dem Gymnastikball ablegen und die Stützposition mit gerader Körperlinie ruhig halten. Ausrüstung: Gymnastikball. Worauf achten: Die instabile Unterlage aktiv über Rumpfspannung ausgleichen, kein Hohlkreuz.' where name = 'Unterarmstütz auf dem Gymnastikball';
update public.exercises set description = 'Ausführung: Auf der Flachbank liegend mit Fußkontakt zum Boden die Langhantel kontrolliert zur Brust absenken und wieder hochdrücken. Ausrüstung: Langhantel, Bank. Worauf achten: Schulterblätter zurückziehen und fixieren, Ellbogen ca. 45° zum Körper, kontrolliert ablassen, Sicherung/Spotter bei hohem Gewicht.' where name = 'Bankdrücken (Flachbank)';
update public.exercises set description = 'Ausführung: Fersen auf dem Gymnastikball ablegen, Hüfte anheben und den Ball anschließend kontrolliert zum Gesäß heranrollen, dann zurückrollen. Ausrüstung: Gymnastikball. Worauf achten: Hüfte während der gesamten Bewegung oben halten, Ball kontrolliert führen, Rumpf fest.' where name = 'Beckenlift mit Beinbeuge am Ball';
update public.exercises set description = 'Ausführung: Auf der Schrägbank (30-45°) liegend Langhantel oder Kurzhanteln kontrolliert zum oberen Brustbereich absenken und wieder hochdrücken. Ausrüstung: Langhantel/Kurzhanteln, Schrägbank. Worauf achten: Schulterblätter fixiert, kontrollierte Bewegungsführung, Ellbogen nicht komplett durchdrücken.' where name = 'Schrägbankdrücken';
update public.exercises set description = 'Ausführung: Mit vorgebeugtem Oberkörper und leicht gebeugten Knien die Langhantel zum Bauch heranziehen, kontrolliert absenken. Ausrüstung: Langhantel. Worauf achten: Rumpf fest, Rücken durchgehend gerade, Ellbogen eng am Körper führen, kein Schwung aus dem unteren Rücken.' where name = 'Vorgebeugtes Rudern (Langhantel)';
update public.exercises set description = 'Ausführung: Seilzug hinter dem Kopf halten und die Unterarme im Ellbogengelenk kontrolliert nach oben strecken, dann zurückführen. Ausrüstung: Kabelzug, Seil. Worauf achten: Oberarme eng am Kopf fixiert, Bewegung ausschließlich im Ellbogengelenk, kein Hohlkreuz.' where name = 'Trizepsstrecken am Seil (über Kopf)';
update public.exercises set description = 'Ausführung: Langhantel im schulterbreiten Griff kontrolliert vom gestreckten Arm zur Schulter hochcurlen, dann langsam absenken. Ausrüstung: Langhantel. Worauf achten: Ellbogen am Körper fixiert, kein Schwungholen aus dem Oberkörper.' where name = 'Bizepscurls (Langhantel)';
update public.exercises set description = 'Ausführung: Wie die Gerätevariante, ohne Zusatzgewicht: hinteren Fuß erhöht ablegen und mit dem vorderen Bein kontrolliert in die Kniebeuge gehen. Ausrüstung: keine, Bank oder Stufe. Worauf achten: Oberkörper aufrecht, kontrollierte Tiefe, vorderes Knie bleibt über dem Fuß.' where name = 'Bulgarian Split Squat (Bodyweight)';
update public.exercises set description = 'Ausführung: Klassischer Liegestütz mit Körper absenken bis zur leichten Dehnung in der Brust und wieder hochdrücken, alternativ mit Medizinball unter einer Hand oder mit Zusammendrücken eines Balls zwischen den Händen für zusätzliche Rumpf-/Brustspannung. Ausrüstung: keine, optional Medizinball. Worauf achten: Körper bildet eine gerade Linie, Rumpf fest, bei Bedarf auf den Knien ausführen.' where name = 'Liegestütz-Varianten';
update public.exercises set description = 'Ausführung: Aus dem Stand den Oberkörper mit geradem Rücken und leicht gebeugten Knien nach vorn absenken, bis eine Dehnung in der Oberschenkelrückseite spürbar ist, dann über die Hüfte wieder aufrichten. Ausrüstung: keine. Worauf achten: Rücken durchgehend gerade, Bewegung kommt aus der Hüfte statt aus dem unteren Rücken.' where name = 'Good Mornings (Bodyweight)';
update public.exercises set description = 'Ausführung: In Bauchlage Arme und Beine gleichzeitig leicht vom Boden abheben und kurz ruhig halten, dann kontrolliert absenken. Ausrüstung: Matte. Worauf achten: Bewegung kommt aus dem Rücken, kein Überstrecken des Nackens, Blick zum Boden gerichtet lassen.' where name = 'Superman';
update public.exercises set description = 'Ausführung: Mit gefüllten Wasserflaschen in beiden Händen die Arme seitlich langsam kreisen lassen, Richtung nach einigen Kreisen wechseln. Ausrüstung: Wasserflaschen oder leichte Kurzhanteln. Worauf achten: Kontrollierte, nicht zu große Kreisbewegung, Schultern unten lassen.' where name = 'Schulterkreisen mit Wasserflaschen';
update public.exercises set description = 'Ausführung: Aus dem Ausfallschritt heraus hochspringen und die Beine in der Luft wechseln, um im Ausfallschritt der anderen Seite zu landen. Ausrüstung: keine, rutschfester Untergrund. Worauf achten: Weiche Landung über den Fußballen, Rumpf während des Sprungs stabil, vorderes Knie fällt beim Landen nicht nach innen.' where name = 'Plyo-Ausfallschritte';
update public.exercises set description = 'Ausführung: Wie die Grundvariante mit dem Gymnastikball, ggf. mit leichtem, kontrolliertem Vor- und Zurückrollen der Unterarme. Ausrüstung: Gymnastikball. Worauf achten: Rumpfspannung durchgehend halten, kein Hohlkreuz.' where name = 'Unterarmstütz-Varianten auf dem Ball';
update public.exercises set description = 'Ausführung: Einbeinig stehen, Oberkörper kontrolliert nach vorn absenken, freies Bein nach hinten strecken, bis Oberkörper und Bein eine Linie bilden, Seite wechseln. Ausrüstung: keine. Worauf achten: Ruhiger Stand, Rumpf aktiv stabilisieren, Standbein leicht gebeugt.' where name = 'Standwaage (ohne Zusatzgerät)';
update public.exercises set description = 'Ausführung: Mehrere Runden im Wechsel aus einer Belastungsphase (z. B. Kniebeugen, Liegestütz, Ausfallschritte) und einer kurzen Erholungsphase durchführen. Ausrüstung: keine. Worauf achten: Saubere Ausführung geht vor Tempo, auch unter Ermüdung, Übungsauswahl und Belastung an die eigene Fitness anpassen.' where name = 'HIIT-Zirkel (freie Übungsauswahl)';
update public.exercises set description = 'Ausführung: Kettlebell mit gestreckten Armen aus der kraftvollen Hüftstreckung nach vorn-oben schwingen lassen, Schwung kommt aus der Hüfte, nicht aus den Armen oder Schultern. Ausrüstung: Kettlebell. Worauf achten: Rücken neutral und gerade, Bewegung aus der Hüfte, nicht aus dem unteren Rücken, Knie nur leicht beugen.' where name = 'Kettlebell Swings';
update public.exercises set description = 'Ausführung: Auf eine stabile Erhöhung (Kasten, Bank oder Treppenstufe) steigen und kontrolliert wieder heruntersteigen, Seite wechseln. Ausrüstung: Kasten oder stabile Erhöhung. Worauf achten: Ganze Fußsohle aufsetzen, Knie in Fußrichtung und fällt nicht nach innen, kontrolliertes Tempo.' where name = 'Step-Ups';
update public.exercises set description = 'Ausführung: Am Rudergerät im Wechsel zügige Intervalle und lockere Erholungsphasen rudern, Beine-Rücken-Arme-Sequenz konstant halten. Ausrüstung: Rudergerät. Worauf achten: Saubere Zugreihenfolge Beine-Rücken-Arme, Rücken während des Zugs neutral, Intensität an die eigene Fitness anpassen.' where name = 'Ruder-Intervalle';
update public.exercises set description = 'Ausführung: In leichter Kniebeuge-Position beide Seile abwechselnd oder gleichzeitig wellenförmig auf- und abbewegen, im Wechsel mit kurzen Erholungsphasen. Ausrüstung: Battle Ropes. Worauf achten: Rumpf stabil, Bewegung kommt aus Schultern und Armen, Knie leicht gebeugt für einen stabilen Stand.' where name = 'Battle Ropes';
update public.exercises set description = 'Ausführung: Aus der Liegestütz-Position mit angespanntem Rumpf die Knie zügig abwechselnd zur Brust ziehen. Ausrüstung: keine. Worauf achten: Hüfte tief und auf Schulterhöhe halten, Rumpf während des gesamten Tempos stabil, Hände bleiben unter den Schultern.' where name = 'Mountain Climbers';
update public.exercises set description = 'Ausführung: Aus dem Stand in die Liegestütz-Position abspringen, einen Liegestütz ausführen, dann wieder aufspringen mit Strecksprung. Ausrüstung: keine. Worauf achten: Kontrollierte Landung, Rumpf während der Liegestützphase stabil halten, Tempo an die eigene Technik anpassen.' where name = 'Burpees';
update public.exercises set description = 'Ausführung: Sitzhöhe so einstellen, dass die Griffe auf Brusthöhe liegen, dann auf der Maschine sitzend die Griffe nach vorn drücken, bis die Arme fast gestreckt sind, dann kontrolliert bis zur leichten Dehnung in der Brust zurückführen. Ausrüstung: Brustpresse-Maschine. Worauf achten: Rücken und Kopf bleiben durchgehend an der Lehne, Schultern nicht nach vorn ziehen oder hochziehen, Ellbogen nicht komplett durchdrücken, Bewegung ohne Schwung ausführen.' where name = 'Brustpresse an der Maschine';
update public.exercises set description = 'Ausführung: Auf der Flachbank liegend mit festem Fußkontakt zum Boden die Kurzhanteln von Brusthöhe nach oben drücken, bis die Arme fast gestreckt sind, dann kontrolliert bis auf Brusthöhe absenken. Ausrüstung: Kurzhanteln, Bank. Worauf achten: Schulterblätter zurückziehen und während der gesamten Bewegung fixieren, Ellbogen ca. 45° zum Körper, gleichmäßige Bewegung beider Arme, Hanteln beim Absenken nicht unkontrolliert nach außen kippen lassen.' where name = 'Kurzhantel-Bankdrücken (Flachbank)';
update public.exercises set description = 'Ausführung: Auf der Flachbank liegend die Kurzhanteln über der Brust mit leicht gebeugten Ellbogen halten, dann seitlich in einer Bogenbewegung absenken, bis eine leichte Dehnung in der Brust spürbar ist, dann in derselben Bogenbewegung wieder zusammenführen. Ausrüstung: Kurzhanteln, Bank. Worauf achten: Ellbogenwinkel während der gesamten Bewegung beibehalten, nicht tiefer absenken als schulterschonend möglich, kontrolliert und ohne Schwung ausführen, moderates Gewicht wählen, da die Schulter in der Dehnungsposition wenig Schutz hat.' where name = 'Kurzhantel-Fliegende (Flachbank)';
update public.exercises set description = 'Ausführung: An der Butterfly-Maschine mit an der Lehne anliegendem Rücken sitzen, die Arme bzw. Polster vor dem Körper kontrolliert zusammenführen, dann bis zur leichten Dehnung in der Brust wieder öffnen. Ausrüstung: Butterfly- bzw. Pec-Deck-Maschine. Worauf achten: Rücken durchgehend an der Lehne, Bewegung aus der Brust einleiten statt aus den Schultern, nicht in der Endposition einrasten lassen, Arme nicht weiter öffnen als schulterschonend möglich.' where name = 'Butterfly an der Maschine';
update public.exercises set description = 'Ausführung: Am Kabelturm mit einem Bein leicht nach vorn versetzt stehen, beide Griffe von oben-außen mit leicht gebeugten Ellbogen in einer Bogenbewegung vor dem Körper zusammenführen, dann kontrolliert zurück bis zur leichten Dehnung in der Brust führen. Ausrüstung: Kabelzug mit zwei hohen Umlenkrollen. Worauf achten: Leichte Vorbeuge und stabiler Stand, Ellbogenwinkel beibehalten, Bewegung kontrolliert und mit konstanter Spannung im Kabel ausführen, nicht zu weit zurückführen, um die Schulter zu schonen.' where name = 'Kabelzug-Fliegende (Cable Crossover)';
update public.exercises set description = 'Ausführung: Sitzend mit leicht gebeugten Knien und aufgerichtetem Oberkörper am Rudergerät bzw. Kabelzug den Griff zum Bauch heranziehen, Schulterblätter dabei zusammenziehen, kontrolliert bis zur fast vollen Armstreckung zurückführen. Ausrüstung: Rudermaschine oder Kabelzug mit V-Griff. Worauf achten: Oberkörper aufrecht und ruhig halten, kein Vor- und Zurückschaukeln, Zug aus dem Rücken statt aus den Armen einleiten, Ellbogen eng am Körper führen.' where name = 'Rudermaschine sitzend';
update public.exercises set description = 'Ausführung: Mit einem Knie und der gleichseitigen Hand auf der Bank abstützen, Rücken gerade und parallel zum Boden ausrichten, die Kurzhantel mit der anderen Hand seitlich am Körper nach oben-hinten ziehen, kontrolliert bis zur vollen Armstreckung absenken. Ausrüstung: Kurzhantel, Bank. Worauf achten: Rücken gerade, Rumpf stabil, keine Rotation im Oberkörper, Ellbogen eng am Körper nach oben-hinten führen.' where name = 'Einarmiges Kurzhantelrudern';
update public.exercises set description = 'Ausführung: Auf der Kniestütze der Assistenzmaschine mit schulterbreitem Griff den Körper durch Zug der Rückenmuskulatur nach oben ziehen, bis das Kinn etwa auf Stangenhöhe ist, kontrolliert bis zur fast vollen Armstreckung absenken. Ausrüstung: Klimmzug-Assistenzmaschine. Worauf achten: Gewichtsunterstützung so wählen, dass die Bewegung sauber und ohne Schwung gelingt, Schultern aktiv nach unten ziehen, Rumpf während der Bewegung stabil halten.' where name = 'Klimmzüge an der Assistenzmaschine';
update public.exercises set description = 'Ausführung: An der Rückenstrecker-Maschine mit an der Polsterung fixierter Hüfte den Oberkörper aus der Vorbeuge kontrolliert bis zur neutralen Wirbelsäulenstellung aufrichten, langsam wieder absenken. Ausrüstung: Rückenstrecker-Maschine. Worauf achten: Bewegung aus der Hüfte einleiten, keine Überstreckung ins Hohlkreuz am oberen Punkt, kontrolliertes Tempo ohne Schwung, bei Rückenbeschwerden die Bewegungsamplitude reduzieren.' where name = 'Rückenstrecker an der Maschine';
update public.exercises set description = 'Ausführung: Sitzend mit dem Rücken an der Lehne die Griffe von Schulterhöhe nach oben drücken, bis die Arme fast gestreckt sind, kontrolliert wieder bis auf Schulterhöhe absenken. Ausrüstung: Schulterpresse-Maschine. Worauf achten: Rücken durchgehend an der Lehne, kein Hohlkreuz im unteren Rücken, Bewegung gleichmäßig und ohne Einrasten in der Endposition, Handgelenke gerade über den Ellbogen halten.' where name = 'Schulterpresse an der Maschine';
update public.exercises set description = 'Ausführung: Im hüftbreiten Stand mit leicht gebeugten Knien die Kurzhanteln seitlich bis auf Schulterhöhe anheben, kontrolliert absenken. Ausrüstung: Kurzhanteln. Worauf achten: Leichte Beugung im Ellbogen beibehalten, kein Schwung aus Beinen/Hüfte, Schultern unten lassen statt hochzuziehen, nicht über Schulterhöhe anheben.' where name = 'Seitheben mit Kurzhanteln';
update public.exercises set description = 'Ausführung: Im hüftbreiten Stand die Kurzhanteln vor dem Körper mit leicht gebeugten Ellbogen bis auf Schulterhöhe anheben, kontrolliert absenken. Ausrüstung: Kurzhanteln. Worauf achten: Rumpf stabil, kein Schwung aus dem unteren Rücken, Bewegung abwechselnd oder beidarmig kontrolliert ausführen, Schultern unten lassen.' where name = 'Frontheben mit Kurzhanteln';
update public.exercises set description = 'Ausführung: Am Kabelzug mit Seilgriff auf Gesichtshöhe den Zug bei aufrechtem Oberkörper zum Gesicht heranziehen, Ellbogen dabei nach außen-oben führen, kontrolliert bis zur fast vollen Armstreckung zurückführen. Ausrüstung: Kabelzug mit Seilgriff. Worauf achten: Schulterblätter aktiv zusammenziehen, Ellbogen bleiben auf Schulterhöhe, kein Zug aus dem unteren Rücken, leichtes bis moderates Gewicht für saubere Technik wählen.' where name = 'Face Pulls am Kabelzug';
update public.exercises set description = 'Ausführung: Rücklings an der Butterfly-Maschine mit Brustkontakt zur Polsterung sitzend die Arme seitlich mit leicht gebeugten Ellbogen nach hinten führen, Schulterblätter zusammenziehen, kontrolliert zurückführen. Ausrüstung: Butterfly-Maschine (Reverse-Position). Worauf achten: Bewegung aus dem oberen Rücken statt aus den Armen einleiten, aufrechte Sitzposition, kein Hochziehen der Schultern.' where name = 'Reverse Butterfly an der Maschine';
update public.exercises set description = 'Ausführung: Im Stand oder Sitzen mit herabhängenden Armen die Kurzhanteln durch Beugen der Ellbogen nach oben führen, bis die Unterarme senkrecht stehen, kontrolliert bis zur fast vollen Streckung absenken. Ausrüstung: Kurzhanteln. Worauf achten: Ellbogen bleiben während der gesamten Bewegung am Körper fixiert, kein Schwung aus dem Oberkörper oder den Schultern.' where name = 'Bizepscurls mit Kurzhanteln';
update public.exercises set description = 'Ausführung: Wie Bizepscurls, jedoch mit neutralem Griff (Handflächen zeigen zueinander) während der gesamten Auf- und Abwärtsbewegung ausführen. Ausrüstung: Kurzhanteln. Worauf achten: Handgelenke gerade halten, Ellbogen am Körper fixiert, kontrolliertes Tempo ohne Schwung aus dem Oberkörper.' where name = 'Hammercurls mit Kurzhanteln';
update public.exercises set description = 'Ausführung: Am unteren Kabelzug mit aufrechtem Stand die Ellbogen beugen und die Stange oder das Seil nach oben führen, kontrolliert bis zur fast vollen Armstreckung absenken. Ausrüstung: Kabelzug mit Stangen- oder Seilgriff. Worauf achten: Oberkörper ruhig halten, Ellbogen am Körper fixiert, gleichmäßiger Zug ohne Schwung aus Hüfte oder Rücken.' where name = 'Bizepscurls am Kabelzug';
update public.exercises set description = 'Ausführung: An der Maschine sitzend mit Oberarmen nah am Körper die Griffe durch Strecken der Ellbogen nach unten bzw. vorn drücken, kontrolliert bis zur Ausgangsposition zurückführen. Ausrüstung: Trizepsdrücker-Maschine. Worauf achten: Oberarme bleiben während der gesamten Bewegung ruhig und am Körper, Bewegung ausschließlich im Ellbogengelenk, Ellbogen nicht mit Schwung durchdrücken.' where name = 'Trizepsdrücken an der Maschine';
update public.exercises set description = 'Ausführung: Sitzend oder stehend eine Kurzhantel mit beiden Händen über Kopf halten, Ellbogen kontrolliert beugen und die Hantel hinter den Kopf bis zur leichten Dehnung im Trizeps absenken, dann wieder strecken. Ausrüstung: Kurzhantel. Worauf achten: Ellbogen zeigen nach vorn und bleiben während der gesamten Bewegung nah am Kopf, Rumpf stabil, kein Hohlkreuz, moderates Gewicht wählen, da die Ellbogen in dieser Position stärker belastet werden.' where name = 'Kurzhantel-Trizepsstrecken (über Kopf)';
update public.exercises set description = 'Ausführung: Am oberen Kabelzug mit leicht vorgebeugtem Oberkörper die Ellbogen am Körper fixiert strecken, bis die Arme fast gerade sind, kontrolliert bis zum rechten Winkel im Ellbogen zurückführen. Ausrüstung: Kabelzug mit Stangen- oder Seilgriff. Worauf achten: Oberarme bleiben während der gesamten Bewegung am Oberkörper fixiert, kein Mitschwingen aus Schulter oder Rumpf, Handgelenke gerade halten.' where name = 'Trizeps-Pushdown am Kabelzug';
update public.exercises set description = 'Ausführung: An der Beinpresse mit hüftbreit auf der Plattform platzierten Füßen die Plattform durch Strecken der Beine nach oben bzw. vorn drücken, kontrolliert bis zum rechten Winkel im Knie absenken. Ausrüstung: Beinpresse. Worauf achten: Knie in Fußrichtung, unterer Rücken bleibt durchgehend an der Lehne, Bewegung kontrolliert ohne Durchstoßen der Knie am oberen Punkt, Gesäß nicht von der Sitzfläche abheben.' where name = 'Beinpresse';
update public.exercises set description = 'Ausführung: Sitzend mit dem Rücken an der Lehne und den Polstern auf den Schienbeinen die Unterschenkel durch Strecken der Knie anheben, in der oberen Position kurz halten, kontrolliert absenken. Ausrüstung: Beinstrecker-Maschine. Worauf achten: Rücken durchgehend an der Lehne, Bewegung kontrolliert ohne Schwung, Knie am oberen Punkt nicht ruckartig durchdrücken.' where name = 'Beinstrecker an der Maschine';
update public.exercises set description = 'Ausführung: Liegend oder sitzend an der Maschine mit den Polstern an den Fersen die Unterschenkel durch Beugen der Knie zum Gesäß heranziehen, kontrolliert bis zur fast vollen Streckung zurückführen. Ausrüstung: Beinbeuger-Maschine (liegend oder sitzend). Worauf achten: Hüfte bleibt durchgehend auf der Auflage, Bewegung kontrolliert ohne Schwung ausführen, kein Hohlkreuz durch Abheben des Beckens.' where name = 'Beinbeuger an der Maschine';
update public.exercises set description = 'Ausführung: Stehend an der Maschine mit den Fußballen auf der Stufe auf die Fußballen drücken, bis die Fersen maximal angehoben sind, kontrolliert bis zur deutlichen Dehnung in der Wade absenken. Ausrüstung: Wadenheben-Maschine (stehend). Worauf achten: Volle Bewegungsamplitude nutzen, Knie leicht gestreckt, kontrolliertes Tempo ohne Wippen oder Abfedern am unteren Punkt.' where name = 'Wadenheben stehend an der Maschine';
update public.exercises set description = 'Ausführung: Sitzend an der Maschine mit den Polstern auf den Knien und den Fußballen auf der Stufe auf die Fußballen drücken, Fersen maximal anheben, kontrolliert bis zur Dehnung absenken. Ausrüstung: Wadenheben-Maschine (sitzend). Worauf achten: Volle Bewegungsamplitude, kontrolliertes Tempo, kein Wippen mit Schwung, Gewicht moderat wählen, um die Knie nicht zu überlasten.' where name = 'Wadenheben sitzend an der Maschine';
update public.exercises set description = 'Ausführung: Sitzend an der Maschine mit den Außenseiten der Knie an den Polstern die Beine gegen den Widerstand zusammenführen, kontrolliert bis zur angenehmen Dehnung wieder öffnen. Ausrüstung: Adduktorenmaschine. Worauf achten: Rücken an der Lehne, Bewegung langsam und kontrolliert, kein Einrasten in der Endposition, Öffnungsweite nicht bis in den schmerzhaften Bereich steigern.' where name = 'Adduktorenmaschine';
update public.exercises set description = 'Ausführung: Sitzend an der Maschine mit den Außenseiten der Knie an den Polstern die Beine gegen den Widerstand nach außen drücken, kontrolliert wieder zusammenführen. Ausrüstung: Abduktorenmaschine. Worauf achten: Rücken an der Lehne, Bewegung langsam und kontrolliert ausführen, Oberkörper dabei ruhig halten statt mitzuschwingen.' where name = 'Abduktorenmaschine';
update public.exercises set description = 'Ausführung: Mit dem oberen Rücken an einer Bank abgestützt, Füße hüftbreit nah am Gesäß aufgestellt und der Langhantel mit Polster über der Hüfte die Hüfte kraftvoll nach oben strecken, bis Oberkörper und Oberschenkel eine Linie bilden, kontrolliert absenken. Ausrüstung: Langhantel (mit Polster), Bank. Worauf achten: Gesäß am oberen Punkt aktiv anspannen, kein Hohlkreuz, Kinn leicht zur Brust, Knie zeigen während der Bewegung in Fußrichtung.' where name = 'Hüftstoßen mit der Langhantel (Hip Thrust)';
update public.exercises set description = 'Ausführung: Mit einer Fußmanschette am unteren Kabelzug und leicht nach vorn geneigtem Oberkörper das gestreckte Bein kontrolliert nach hinten-oben führen, kontrolliert zurückführen. Ausrüstung: Kabelzug mit Fußmanschette. Worauf achten: Rumpf stabil, Bewegung aus dem Gesäß statt aus dem unteren Rücken, kein Schwung, Standbein leicht gebeugt für sicheren Halt.' where name = 'Kabelzug-Kickback';
update public.exercises set description = 'Ausführung: Kniend vor dem hohen Kabelzug mit Seilgriff neben dem Kopf den Oberkörper durch Anspannen der Bauchmuskulatur nach unten Richtung Oberschenkel einrollen, kontrolliert zurückführen. Ausrüstung: Kabelzug mit Seilgriff. Worauf achten: Bewegung aus der Bauchmuskulatur einleiten, Hüfte bleibt weitgehend ruhig, kein Ziehen mit den Armen, Nacken entspannt lassen.' where name = 'Kabel-Crunches (kniend)';
update public.exercises set description = 'Ausführung: Hängend an der Klimmzugstange oder im Dip-/Klimmzugturm mit Armstütze und stabilisiertem Oberkörper die gestreckten oder angewinkelten Beine kontrolliert nach oben führen, langsam bis zur fast vollen Streckung absenken. Ausrüstung: Klimmzugstange oder Dip-/Klimmzugturm mit Armstütze. Worauf achten: Schwungfrei arbeiten, Rumpf leicht einrollen statt nur die Hüfte zu beugen, bei Anfängern mit angewinkelten Beinen beginnen.' where name = 'Beinheben hängend';
update public.exercises set description = 'Ausführung: Gehen oder Laufen auf dem Laufband, Tempo und Steigung schrittweise über die Konsole einstellen und erst starten, wenn ein sicherer Stand gefunden ist. Ausrüstung: Laufband. Worauf achten: Aufrechte Haltung, Blick nach vorn statt nach unten, Landung über den Mittelfuß, Notausschalter/Sicherheitsclip nutzen, Intensität über Tempo/Steigung oder Herzfrequenz steuern.' where name = 'Laufband';
update public.exercises set description = 'Ausführung: Auf den Pedalen mit aufrechtem Oberkörper stehend die ellipsenförmige Bewegung mit aktivem Armeinsatz an den Griffen ausführen, Widerstand schrittweise über die Konsole einstellen. Ausrüstung: Crosstrainer/Ellipsentrainer. Worauf achten: Aufrechte Haltung, gleichmäßiger Tritt, Gewicht nicht einseitig auf Fersen oder Fußballen verlagern, Knie in Fußrichtung führen.' where name = 'Crosstrainer (Ellipsentrainer)';
update public.exercises set description = 'Ausführung: Im gleichmäßigen Rhythmus mit aufrechter Haltung auf die Pedale des Steppers treten, Widerstand/Tempo schrittweise über die Konsole einstellen. Ausrüstung: Stepper. Worauf achten: Aufrechte Haltung, kein Abstützen mit vollem Körpergewicht auf den Griffen, Schritte kontrolliert statt mit Schwung, Fuß vollständig auf dem Pedal aufsetzen.' where name = 'Stepper';
update public.exercises set description = 'Ausführung: Kontinuierliches Treppensteigen auf dem Gerät mit aufrechtem Oberkörper, Tempo schrittweise über die Konsole einstellen. Ausrüstung: Stairmaster/Treppensteiger. Worauf achten: Aufrechte Haltung, Fuß vollständig auf der Stufe aufsetzen, Griffe nur zur Balance statt zum Abstützen nutzen, nicht auf die Zehenspitzen verlagern.' where name = 'Stairmaster (Treppensteiger)';
update public.exercises set description = 'Ausführung: Im Sitzen mit Rückenlehne die Sitzposition vor dem Start passend einstellen und gleichmäßig in die Pedale treten, Widerstand schrittweise über die Konsole einstellen. Ausrüstung: Liegerad/Recumbent Bike. Worauf achten: Sitzposition so einstellen, dass die Knie beim Treten nicht vollständig durchgestreckt werden, gleichmäßige Trittfrequenz, Rücken flächig an der Lehne.' where name = 'Liegerad (Recumbent Bike)';
update public.exercises set description = 'Ausführung: Im Sitzen mit korrekt eingestellter Sattelhöhe gleichmäßig in die Pedale treten, Widerstand/Watt schrittweise über die Konsole einstellen. Ausrüstung: Fahrrad-Ergometer. Worauf achten: Sattelhöhe so einstellen, dass die Knie im unteren Punkt leicht gebeugt bleiben, aufrechter Oberkörper, gleichmäßige Trittfrequenz, Knie beim Treten in Fußrichtung führen.' where name = 'Fahrrad-Ergometer';
update public.exercises set description = 'Ausführung: An der Stange im Ristgriff etwas breiter als schulterbreit hängen, Schulterblätter zuerst leicht nach unten ziehen, dann den Körper durch Zug der Rückenmuskulatur nach oben ziehen, bis das Kinn über der Stange ist, danach kontrolliert bis zum vollständig gestreckten Arm absenken. Ausrüstung: Klimmzugstange. Worauf achten: Schultern aktiv nach unten und hinten ziehen, Rumpf leicht anspannen, kein Schwungholen (Kipping) bei Kraftfokus, Bewegung im vollen Bewegungsradius bis zur Streckung ausführen.' where name = 'Klimmzug (Pull-Up)';
update public.exercises set description = 'Ausführung: Am Barren mit gestreckten Armen abstützen, Schultern nach unten ziehen, Oberkörper leicht nach vorn neigen, kontrolliert bis ca. 90° Ellbogenwinkel absenken, dann kraftvoll wieder hochdrücken. Ausrüstung: Dip-Barren. Worauf achten: Schultern nicht zu tief absinken lassen, um das Schultergelenk zu schonen, Ellbogen zeigen leicht nach hinten statt weit nach außen, Rumpf während der gesamten Bewegung stabil halten.' where name = 'Dips am Barren';
update public.exercises set description = 'Ausführung: Einbeinig stehen, freies Bein gestreckt nach vorn anheben, Arme zur Balance nach vorn ausstrecken, kontrolliert so tief wie sauber möglich absenken, ohne die Balance zu verlieren, dann kraftvoll über die Ferse wieder hochdrücken. Ausrüstung: keine, optional Festhalten an einem festen Punkt zur Unterstützung oder eine Erhöhung, um die Tiefe zu reduzieren. Worauf achten: Knie zeigt durchgehend in Richtung der Fußspitze und fällt nicht nach innen, Rumpf bleibt aufrecht, bei Balanceproblemen die Tiefe reduzieren statt die Kontrolle zu verlieren.' where name = 'Pistol Squat';
update public.exercises set description = 'Ausführung: Im Kniestand die Füße sicher fixieren lassen (Partner oder Gerät), Oberkörper langsam und kontrolliert aus der Knie- und Hüftlinie nach vorn absenken, mit den Händen kurz vor dem Boden abfangen und zurückdrücken. Ausrüstung: Fixierung für die Füße (Partner, Nordic-Curl-Gerät oder Langhantel unter einem Möbelstück), Matte für die Knie. Worauf achten: Bewegung so lange wie möglich aktiv über die Beinrückseite abbremsen statt einfach nach vorn zu kippen, Rumpf und Hüfte bleiben durchgehend in einer Linie, bei Anfängern die Bewegungsamplitude reduzieren.' where name = 'Nordic Hamstring Curl';
update public.exercises set description = 'Ausführung: In Rückenlage Arme über den Kopf und Beine gestreckt leicht vom Boden abheben, unteren Rücken aktiv fest gegen den Boden drücken, Position ruhig und ohne Zittern halten. Ausrüstung: Matte. Worauf achten: Unterer Rücken bleibt durchgehend am Boden, kein Hohlkreuz, gleichmäßig weiteratmen statt die Luft anzuhalten, bei Bedarf Beine höher oder Arme näher am Körper positionieren, um die Spannung zu reduzieren.' where name = 'Hollow Body Hold';
update public.exercises set description = 'Ausführung: Im Stütz (Boden, Barren oder Parallelen) die Schultern aktiv nach unten drücken und die Arme strecken, die gestreckten Beine waagerecht nach vorn anheben und die Position ruhig halten. Ausrüstung: Stützgriffe, Barren oder Boden. Worauf achten: Schultern durchgehend aktiv nach unten drücken, unterer Rücken nicht ins Hohlkreuz fallen lassen, bei Bedarf die Knie anwinkeln, um die Belastung zu reduzieren.' where name = 'L-Sit';
update public.exercises set description = 'Ausführung: Aus dem hüftbreiten Stand in die Knie gehen, mit kräftigem Armschwung so weit wie kontrolliert möglich nach vorn springen, weich und kontrolliert in der Kniebeuge landen. Ausrüstung: keine, ausreichend Platz und rutschfester Boden. Worauf achten: Weiche Landung über die gesamte Fußsohle, Knie beim Absprung und bei der Landung nicht nach innen fallen lassen, erst den nächsten Sprung einleiten, wenn die Landung stabil steht.' where name = 'Standweitsprung (Broad Jump)';
update public.exercises set description = 'Ausführung: Aus dem Stand mit kräftigem Armschwung explosiv auf eine stabile Erhöhung springen, mit beiden Füßen vollständig auf der Box landen und oben in aufrechter Position mit leicht gebeugten Knien ankommen, kontrolliert wieder herabsteigen. Ausrüstung: stabile Sprungbox oder Bank. Worauf achten: Immer herabsteigen statt herunterspringen, um die Gelenke zu schonen, Boxhöhe konservativ wählen und erst steigern, wenn die Landung sicher sitzt, Schienbein nicht an der Box anstoßen.' where name = 'Box Jump';
update public.exercises set description = 'Ausführung: Im Vierfüßlerstand die Knie knapp über den Boden anheben und Rumpf anspannen, dann diagonal Hand und gegenüberliegenden Fuß gleichzeitig nach vorn bewegen. Ausrüstung: keine, glatter oder gepolsterter Untergrund. Worauf achten: Hüfte bleibt ruhig und tief, kein Auf-und-Ab-Wippen, kleine kontrollierte Schritte statt große Ausfallbewegungen.' where name = 'Bärengang (Bear Crawl)';
update public.exercises set description = 'Ausführung: Im umgekehrten Vierfüßlerstand (Bauch nach oben, Hände und Füße am Boden) die Hüfte aktiv anheben und seitwärts oder vorwärts gehen. Ausrüstung: keine. Worauf achten: Hüfte durchgehend angehoben halten, Schultern über den Handgelenken, Handgelenke bei Beschwerden entlasten, indem die Finger nach außen statt nach hinten zeigen.' where name = 'Krabbengang (Crab Walk)';
update public.exercises set description = 'Ausführung: Im Stand die Hände am Boden ablegen, mit den Händen in den hohen Stütz vorlaufen, kurz stabil halten, anschließend die Füße mit möglichst gestreckten Beinen zu den Händen zurücklaufen. Ausrüstung: keine. Worauf achten: Beine möglichst gestreckt lassen, bei Verspannung der Beinrückseite die Knie leicht beugen, Bewegung langsam und kontrolliert ausführen, Rumpf im Stütz stabil halten.' where name = 'Inchworm';
update public.exercises set description = 'Ausführung: Aus dem tiefen Ausfallschritt den hinteren Fuß aktiv in den Boden drücken, den Ellbogen zum vorderen Fuß führen, anschließend Oberkörper und Arm kontrolliert nach oben rotieren, Blick folgt der Hand, danach die Seite wechseln. Ausrüstung: keine. Worauf achten: Bewegung fließend und im schmerzfreien Bereich ausführen, vorderes Knie bleibt über dem Fuß, Atmung nicht anhalten.' where name = 'World''s Greatest Stretch';
update public.exercises set description = 'Ausführung: Im Sitz beide Beine im 90°-Winkel ablegen (ein Bein nach innen, eines nach außen rotiert), Oberkörper aufrecht und Rumpf leicht angespannt halten, kontrolliert über beide Beine hinweg die Seite wechseln. Ausrüstung: Matte. Worauf achten: Bewegung langsam und ruhig, im schmerzfreien Bereich der Hüfte bleiben, Gesäß möglichst am Boden lassen statt sich abzustützen.' where name = '90/90-Hüftmobilisation';
update public.exercises set description = 'Ausführung: In die tiefstmögliche, saubere Kniebeugeposition absenken und dort entspannt verweilen, ggf. mit den Ellbogen die Knie sanft nach außen drücken. Ausrüstung: keine, optional Festhalten an einem festen Punkt zur Balance. Worauf achten: Fersen bleiben durchgehend am Boden, Rücken bleibt lang statt rund, ruhig weiteratmen und die Position so lange wie angenehm halten.' where name = 'Tiefe Kniebeuge im Halten (Deep Squat Hold)';
update public.exercises set description = 'Ausführung: Rücken, Kopf und Unterarme im rechten Winkel gegen eine Wand pressen, Arme langsam nach oben gleiten lassen und wieder zurück, ohne den Wandkontakt an Unterarmen und Handrücken zu verlieren. Ausrüstung: Wand. Worauf achten: Unterer Rücken bleibt flach an der Wand, kein Hohlkreuz, Bewegung kommt aus dem Schulterblatt, bei Verlust des Wandkontakts die Bewegungsamplitude reduzieren.' where name = 'Wandschieben (Wall Slides)';
update public.exercises set description = 'Ausführung: Eine Kurzhantel oder Kettlebell aufrecht mit beiden Händen vor der Brust halten, Rumpf anspannen und in die Kniebeuge absenken, bis die Ellbogen die Innenseite der Knie berühren, dann durch die Fersen wieder kraftvoll hochdrücken. Ausrüstung: Kurzhantel oder Kettlebell. Worauf achten: Ellbogen zwischen den Knien nach unten führen, Rücken bleibt gerade, Knie in Fußrichtung, beim Absenken einatmen und beim Hochdrücken ausatmen.' where name = 'Goblet Squat';
update public.exercises set description = 'Ausführung: Kurzhanteln nah am Körper vor den Oberschenkeln halten, Hüfte bei fast gestreckten Knien und leicht angespanntem Rumpf nach hinten schieben, Hanteln eng am Bein entlang bis zur Dehnung in der Oberschenkelrückseite absenken, über die Hüftstreckung wieder aufrichten. Ausrüstung: Kurzhanteln. Worauf achten: Rücken durchgehend gerade halten, Bewegung kommt aus der Hüfte, nicht aus dem unteren Rücken, nur so tief absenken, wie der Rücken gerade bleibt.' where name = 'Rumänisches Kreuzheben mit Kurzhanteln';
update public.exercises set description = 'Ausführung: Mit Kurzhanteln in den herabhängenden Händen abwechselnd große Schritte nach vorn machen, hinteres Knie kontrolliert bis kurz über den Boden absenken, über die vordere Ferse wieder aufstehen und den nächsten Schritt einleiten. Ausrüstung: Kurzhanteln. Worauf achten: Vorderes Knie bleibt über dem Fuß und fällt nicht nach innen, Oberkörper bleibt aufrecht, Rumpf während des gesamten Schritts stabil halten.' where name = 'Kurzhantel-Ausfallschritte gehend (Walking Lunges)';
update public.exercises set description = 'Ausführung: Im hohen Liegestützstütz mit breitem, stabilem Stand auf zwei Kurzhanteln abstützen, abwechselnd eine Hantel seitlich eng am Körper zur Hüfte ziehen, Rumpf dabei fest und stabil halten. Ausrüstung: zwei Kurzhanteln. Worauf achten: Becken bleibt gerade und ruhig, kein Verdrehen des Oberkörpers beim Ziehen, Füße breiter stellen für mehr Stabilität.' where name = 'Renegade Row';
update public.exercises set description = 'Ausführung: Kurzhanteln auf Schulterhöhe halten, in die Kniebeuge absenken, dann explosiv aus den Beinen aufstehen und die Hanteln im Schwung über den Kopf drücken, kontrolliert zurück in die Ausgangsposition führen. Ausrüstung: zwei Kurzhanteln. Worauf achten: Bewegung als ein fließender Ablauf aus Beinkraft und Schulterdrücken ausführen, nicht als zwei getrennte Bewegungen, Rumpf während des Überkopfdrückens stabil halten, kein Hohlkreuz.' where name = 'Kurzhantel-Thruster';
update public.exercises set description = 'Ausführung: Kurzhanteln vor der Brust mit Handflächen zum Körper halten, beim Hochdrücken die Hanteln gleichmäßig nach außen rotieren, bis die Handflächen oben nach vorn zeigen, dann kontrolliert in umgekehrter Reihenfolge absenken. Ausrüstung: Kurzhanteln. Worauf achten: Rotation gleichmäßig und kontrolliert ausführen, Rumpf fest, kein Hohlkreuz durch zu starkes Zurücklehnen.' where name = 'Arnold Press';
update public.exercises set description = 'Ausführung: Langhantel in der Armbeuge fest vor dem Körper halten (nicht auf dem Rücken), Rumpf anspannen und in die Kniebeuge absenken, durch die Fersen wieder kraftvoll hochdrücken. Ausrüstung: Langhantel, ggf. Polsterung für die Armbeugen. Worauf achten: Oberkörper bleibt aufrechter als bei der Rückenkniebeuge, Rumpf durchgehend angespannt, Ellbogen zeigen nach unten statt seitlich wegzuklappen.' where name = 'Zercher Squat';
update public.exercises set description = 'Ausführung: Ein Hantelstangenende in einer Ecke oder Landmine-Halterung fixieren, das andere Ende mit einer Hand vor der Schulter greifen und aus einem stabilen Stand schräg nach oben-vorn drücken, kontrolliert zurückführen. Ausrüstung: Langhantel mit Landmine-Halterung. Worauf achten: Rumpf und Beine stabil halten, Bewegung schräg nach oben-vorn statt gerade nach oben führen, Schulter nicht hochziehen.' where name = 'Landmine Press';
update public.exercises set description = 'Ausführung: In jeder Hand eine Kurzhantel oder Kettlebell fest greifen, Rumpf anspannen und mit aufrechter Haltung in kontrolliertem Tempo gehen. Ausrüstung: zwei Kurzhanteln oder Kettlebells. Worauf achten: Schultern nach hinten-unten ziehen, aufrechter Gang ohne einseitiges Absinken der Hüfte, Gewichte bei nachlassender Haltung kontrolliert abstellen statt fallen zu lassen.' where name = 'Farmer''s Walk';
update public.exercises set description = 'Ausführung: Kettlebell mit Schwung aus der Hüfte in die Frontposition an der Schulter "cleanen", Handgelenk dabei locker halten, von dort über den Kopf drücken, kontrolliert zurückführen. Ausrüstung: Kettlebell. Worauf achten: Bewegung zunächst mit leichtem Gewicht sauber erlernen, Ellbogen beim Clean nah am Körper führen, Handgelenk beim Auffangen nicht überstrecken.' where name = 'Kettlebell Clean & Press';
update public.exercises set description = 'Ausführung: Eine Kettlebell aufrecht vor der Brust halten, mit einem Bein einen kontrollierten Schritt nach hinten machen, hinteres Knie Richtung Boden absenken, über die vordere Ferse zurück in den Stand drücken. Ausrüstung: Kettlebell. Worauf achten: Vorderes Knie bleibt über dem Fuß, Oberkörper bleibt aufrecht, Rumpf während des gesamten Schritts stabil halten.' where name = 'Kettlebell Goblet Reverse Lunge';
update public.exercises set description = 'Ausführung: Eine Kurzhantel einarmig auf Schulterhöhe halten, Rumpf fest anspannen und die Hantel kontrolliert nach oben drücken, bis der Arm fast gestreckt ist, dann kontrolliert absenken. Ausrüstung: Kurzhantel. Worauf achten: Rumpf nicht zur Gegenseite neigen lassen, Bewegung kontrolliert führen, kein Hohlkreuz im unteren Rücken.' where name = 'Einarmiges Kurzhantel-Überkopfdrücken';
update public.exercises set description = 'Ausführung: Eine Kurzhantel einseitig locker neben dem Körper halten, Oberkörper kontrolliert und in kleiner Amplitude zur Hantelseite absenken und wieder aufrichten. Ausrüstung: Kurzhantel. Worauf achten: Bewegung rein seitlich ausführen, kein Vor- oder Zurückbeugen des Oberkörpers, geringes Gewicht wählen und die Bewegung nicht bis zum Anschlag forcieren.' where name = 'Kurzhantel-Seitbeuge';
update public.exercises set description = 'Ausführung: In Rückenlage eine Kettlebell mit durchgehend gestrecktem Arm über der Schulter halten und sich über mehrere definierte Zwischenschritte (Ellbogenstütz, Handstütz, Hüftstreckung, Ausfallschritt zum Stand) kontrolliert aufrichten, danach die Bewegung in umgekehrter Reihenfolge rückwärts ausführen. Ausrüstung: Kettlebell (leicht zum Erlernen). Worauf achten: Blick durchgehend zur Hantel, Bewegung zunächst ohne Gewicht üben, bis der Ablauf sauber sitzt, jeden Zwischenschritt kontrolliert und ohne Hektik ausführen.' where name = 'Turkish Get-Up';
update public.exercises set description = 'Ausführung: Breiter Stand mit nach außen gedrehten Füßen, eine Kurzhantel mittig zwischen den Beinen mit beiden Händen greifen, Rücken gerade und Brust aufrichten, dann aus der Hüfte und den Beinen kraftvoll aufrichten. Ausrüstung: eine Kurzhantel oder Kettlebell. Worauf achten: Knie zeigen durchgehend in Fußrichtung nach außen, Rücken bleibt gerade, Hantel nah am Körper führen.' where name = 'Sumo-Kreuzheben mit Kurzhantel';
update public.exercises set description = 'Ausführung: Quer auf einer Bank liegend (nur Schultern aufliegend), Füße fest auf dem Boden und Hüfte tief unter der Bank, eine Kurzhantel mit beiden Händen über der Brust halten und mit leicht gebeugten Armen hinter den Kopf absenken, bis eine deutliche Dehnung im Latissimus spürbar ist, dann kontrolliert zurückführen. Ausrüstung: Kurzhantel, Bank. Worauf achten: Hüfte durchgehend tief halten, Rippenbogen nicht überstrecken, Ellbogenwinkel während der gesamten Bewegung beibehalten, moderates Gewicht wählen, da die Schultern in der Dehnungsposition stark beansprucht werden.' where name = 'Überzüge mit Kurzhantel';
update public.exercises set description = 'Ausführung: Am hohen Kabelzug mit stabilem Stand und leicht vorgebeugtem Oberkörper die Arme fast gestreckt halten und die Stange oder das Seil in einer Bogenbewegung von oben bis vor die Oberschenkel ziehen, kontrolliert zurückführen. Ausrüstung: Kabelzug mit Stangen- oder Seilgriff. Worauf achten: Arme bleiben während der gesamten Bewegung nahezu gestreckt, Bewegung kommt aus dem Latissimus statt aus den Armen, Oberkörper stabil, Rumpf leicht angespannt.' where name = 'Überzüge am Kabelzug';
update public.exercises set description = 'Ausführung: Im Stand oder in Bauchlage das Band mit beiden Händen straffen und in V-Form diagonal über Kopf nach oben-außen ziehen, Schulterblätter dabei zusammenziehen, kontrolliert bis zur Ausgangsposition zurückführen. Ausrüstung: Widerstandsband. Worauf achten: Bewegung kommt aus dem oberen Rücken statt aus den Armen, kein Hohlkreuz, Ellbogen bleiben lang gestreckt, leichten Bandwiderstand wählen, um die Technik sauber zu halten.' where name = 'V-Lift mit Band';
update public.exercises set description = 'Ausführung: In Bauchlage auf einer Schrägbank mit Stirn auf der Polsterung die Arme mit leichten Kurzhanteln diagonal nach vorn-oben in Y-Form anheben, Schulterblätter zusammenziehen, kontrolliert absenken. Ausrüstung: leichte Kurzhanteln, Schrägbank. Worauf achten: Sehr geringes Gewicht wählen, Bewegung langsam und kontrolliert, kein Schwung, Kopf und Nacken entspannt lassen.' where name = 'V-Lift mit Kurzhantel';
update public.exercises set description = 'Ausführung: Ellbogen im 90°-Winkel am Körper fixiert (Handtuch/Kissen unter der Achsel), den Unterarm mit leichter Kurzhantel oder Band langsam nach außen rotieren, bis eine angenehme Spannung in der Schulter spürbar ist, kontrolliert zurückführen. Ausrüstung: leichte Kurzhantel oder Widerstandsband. Worauf achten: Ellbogen bleibt während der gesamten Bewegung am Körper fixiert, sehr geringes Gewicht, Fokus auf die Rotatorenmanschette statt auf Tempo, Bewegung nicht ruckartig ausführen.' where name = 'Außenrotationen für die Schulter';
update public.exercises set description = 'Ausführung: Ellbogen im 90°-Winkel am Körper fixiert, den Unterarm mit leichter Kurzhantel oder Band langsam vor dem Bauch nach innen rotieren, kontrolliert zurückführen. Ausrüstung: leichte Kurzhantel oder Widerstandsband. Worauf achten: Ellbogen bleibt während der gesamten Bewegung fixiert, kontrolliertes Tempo, kein Schwung aus der Schulter, sehr geringes Gewicht wählen.' where name = 'Innenrotationen für die Schulter';
update public.exercises set description = 'Ausführung: Auf der Negativbank (Kopf tiefer als Becken) liegend mit fixierten Beinen die Langhantel kontrolliert vom unteren Brustbereich nach oben drücken, bis die Arme fast gestreckt sind, kontrolliert wieder absenken. Ausrüstung: Langhantel, Negativbank. Worauf achten: Sicherung/Spotter verwenden, Schulterblätter fixiert, Stange kontrolliert und ohne Aufprall im unteren Brustbereich aufsetzen, moderates Gewicht wegen der ungewohnten Kopftieflage wählen.' where name = 'Negativ-Bankdrücken (Langhantel)';
update public.exercises set description = 'Ausführung: Sitzend mit Rückenlehne und Füßen fest auf dem Boden die Kurzhanteln von Schulterhöhe nach oben drücken, bis die Arme fast gestreckt sind, kontrolliert bis auf Schulterhöhe absenken. Ausrüstung: Kurzhanteln, Bank mit Rückenlehne. Worauf achten: Rücken durchgehend an der Lehne, kein Hohlkreuz, Handgelenke gerade über den Ellbogen, Ellbogen nicht komplett durchdrücken.' where name = 'Kurzhantel-Schulterdrücken (sitzend)';
update public.exercises set description = 'Ausführung: Vorgebeugt mit leicht gebeugten Knien und Untergriff (Handflächen nach oben) die Langhantel zum Bauch heranziehen, Ellbogen eng am Körper, kontrolliert bis zur fast vollen Armstreckung absenken. Ausrüstung: Langhantel. Worauf achten: Rücken gerade und Oberkörperwinkel während der gesamten Bewegung stabil halten, kein Schwung aus dem unteren Rücken, Rumpf angespannt.' where name = 'Langhantelrudern im Untergriff';
update public.exercises set description = 'Ausführung: Über der T-Bar-Stange stehend, Oberkörper vorgebeugt und Rücken gerade, den Griff zum Bauch heranziehen, Schulterblätter zusammenziehen, kontrolliert bis zur fast vollen Armstreckung absenken. Ausrüstung: T-Bar-Rudergerät oder Langhantel in der Ecke mit V-Griff. Worauf achten: Rücken während der gesamten Bewegung gerade, Knie leicht gebeugt, Zug aus dem Rücken statt aus den Armen, kein Schwung aus dem unteren Rücken.' where name = 'T-Bar-Rudern';
update public.exercises set description = 'Ausführung: Mit fast gestreckten Beinen und angespanntem Rumpf die Langhantel eng am Körper entlang absenken, bis eine deutliche Dehnung in der Oberschenkelrückseite spürbar ist, dann über die Hüftstreckung wieder aufrichten. Ausrüstung: Langhantel. Worauf achten: Rücken durchgehend gerade, Bewegung kommt aus der Hüfte statt aus dem unteren Rücken, Stange bleibt körpernah, nur so tief absenken, wie der Rücken gerade bleibt.' where name = 'Rumänisches Kreuzheben (Langhantel)';
update public.exercises set description = 'Ausführung: Die Langhantel vorn auf den Schultern ablegen (Clean-Griff oder verschränkte Arme), Rumpf anspannen, in die Kniebeuge absenken und über die Fersen kraftvoll wieder aufstehen. Ausrüstung: Langhantel, ggf. Squat-Rack. Worauf achten: Oberkörper möglichst aufrecht halten, Ellbogen hoch, Knie in Fußrichtung, aus dem Squat-Rack in Griffhöhe absetzen, um sicher ein- und auszusteigen.' where name = 'Frontkniebeuge (Langhantel)';
update public.exercises set description = 'Ausführung: Mit dem Rücken flächig an der geneigten Rückenplatte der Maschine und hüftbreit platzierten Füßen in die Kniebeuge absenken, dann durch Strecken der Beine kontrolliert wieder aufstehen. Ausrüstung: Hackenschmidt-Maschine. Worauf achten: Rücken bleibt durchgehend an der Platte, Knie in Fußrichtung, kontrolliertes Tempo ohne Durchstoßen der Knie am oberen Punkt, Sicherungsarretierung erst nach vollständigem Stand lösen.' where name = 'Hackenschmidt-Maschine (Hack Squat)';
update public.exercises set description = 'Ausführung: Mit der Langhantel im Nacken und stabilem Stand einen großen Schritt rückwärts setzen, das hintere Knie kontrolliert Richtung Boden absenken, dann über die vordere Ferse zurück in den Stand drücken. Ausrüstung: Langhantel. Worauf achten: Oberkörper aufrecht, vorderes Knie bleibt über dem Fuß und fällt nicht nach innen, kontrolliertes Tempo, Rumpf während des gesamten Schritts stabil.' where name = 'Rückwärtiger Ausfallschritt mit der Langhantel';
update public.exercises set description = 'Ausführung: Sitzend mit breitem Stand den Ellbogen an der Innenseite des Oberschenkels abstützen und die Kurzhantel durch Beugen des Arms nach oben führen, kontrolliert bis zur fast vollen Streckung absenken. Ausrüstung: Kurzhantel, Bank. Worauf achten: Oberarm bleibt während der gesamten Bewegung fixiert, Bewegung isoliert im Ellbogengelenk, kein Schwung aus der Schulter.' where name = 'Konzentrationscurls mit Kurzhantel';
update public.exercises set description = 'Ausführung: Auf der Flachbank liegend mit festem Fußkontakt zum Boden die Langhantel mit schulterbreitem oder engerem Griff von der Brust nach oben drücken, Ellbogen eng am Körper führen, kontrolliert bis zur Brust absenken. Ausrüstung: Langhantel, Bank. Worauf achten: Ellbogen zeigen nach hinten statt nach außen, Handgelenke gerade, Sicherung/Spotter bei hohem Gewicht verwenden, Stange kontrolliert ohne Aufprall auf der Brust aufsetzen.' where name = 'Enges Bankdrücken (Close-Grip)';
update public.exercises set description = 'Ausführung: Auf der Kniestütze der Assistenzmaschine mit gestreckten Armen starten und den Oberkörper zwischen den Griffen kontrolliert absenken, bis die Ellbogen etwa 90° gebeugt sind, dann wieder nach oben drücken. Ausrüstung: Dip-/Klimmzug-Assistenzmaschine. Worauf achten: Gewichtsunterstützung so wählen, dass die Bewegung sauber gelingt, leichte Vorlage für mehr Brust- oder aufrechte Haltung für mehr Trizepsbeteiligung, Schultern nicht zu tief absinken lassen.' where name = 'Dips an der Assistenzmaschine';
update public.exercises set description = 'Ausführung: Im aufrechten Stand die Langhantel mit gestreckten Armen vor dem Körper halten und die Schultern gerade nach oben Richtung Ohren ziehen, kurz halten, kontrolliert absenken. Ausrüstung: Langhantel. Worauf achten: Keine Rollbewegung in den Schultern, Bewegung rein vertikal, Nacken entspannt lassen, kein Schwung aus den Knien.' where name = 'Shrugs mit der Langhantel';
update public.exercises set description = 'Ausführung: Im aufrechten Stand mit einer Kurzhantel in jeder herabhängenden Hand die Schultern gerade nach oben ziehen, kurz halten, kontrolliert absenken. Ausrüstung: Kurzhanteln. Worauf achten: Keine Rollbewegung, Bewegung rein vertikal, aufrechter Stand, Nacken entspannt lassen.' where name = 'Shrugs mit Kurzhanteln';
update public.exercises set description = 'Ausführung: Seitlich zum unteren Kabelzug stehend mit Fußmanschette das äußere Bein gestreckt vor dem Standbein nach innen führen, kontrolliert zurückführen. Ausrüstung: Kabelzug mit Fußmanschette. Worauf achten: Oberkörper stabil, Bewegung kontrolliert ohne Schwung, Halt am Gerät zur Balance, Standbein leicht gebeugt.' where name = 'Beinadduktion am Kabelzug';
update public.exercises set description = 'Ausführung: Seitlich zum unteren Kabelzug stehend mit Fußmanschette das innere Bein gestreckt seitlich vom Körper wegführen, kontrolliert zurückführen. Ausrüstung: Kabelzug mit Fußmanschette. Worauf achten: Oberkörper aufrecht, Bewegung aus der Hüfte statt aus dem Rumpf, kein Ausweichen ins Hohlkreuz, Standbein leicht gebeugt.' where name = 'Beinabduktion am Kabelzug';
update public.exercises set description = 'Ausführung: Die Oberarme flächig auf der Schrägpolsterung des Scott-Pults ablegen und die SZ-Stange durch Beugen der Ellbogen nach oben führen, kontrolliert bis kurz vor die volle Streckung absenken. Ausrüstung: SZ-Stange, Scott-Pult (Preacher-Bank). Worauf achten: Oberarme bleiben während der gesamten Bewegung auf dem Polster, untere Endposition nicht mit Schwung durchdrücken, um den Ellbogen zu schonen.' where name = 'Scott-Curls (SZ-Stange)';
update public.exercises set description = 'Ausführung: Vorgebeugt mit einer Hand und dem gleichseitigen Knie auf der Bank abgestützt, den Rücken gerade und den Oberarm parallel zum Rücken halten, den Unterarm mit der Kurzhantel nach hinten strecken, kontrolliert zurückführen. Ausrüstung: Kurzhantel, Bank. Worauf achten: Oberarm bleibt während der gesamten Bewegung ruhig und parallel zum Rücken, Bewegung ausschließlich im Ellbogengelenk, kein Schwung.' where name = 'Trizeps-Kickback mit Kurzhantel';
update public.exercises set description = 'Ausführung: Am unteren Kabelzug mit stabilem Stand und einer Hand den Griff vor dem Körper bis auf Schulterhöhe anheben, kontrolliert absenken. Ausrüstung: Kabelzug mit Einzelgriff. Worauf achten: Leichte Beugung im Ellbogen beibehalten, kein Schwung aus dem Rumpf, konstante Spannung im Kabel, nicht über Schulterhöhe anheben.' where name = 'Kabelzug-Frontheben';
update public.exercises set description = 'Ausführung: Seitlich zum unteren Kabelzug stehend mit der außenliegenden Hand und leicht gebeugtem Ellbogen den Griff seitlich bis auf Schulterhöhe anheben, kontrolliert absenken. Ausrüstung: Kabelzug mit Einzelgriff. Worauf achten: Oberkörper stabil, kein Schwung aus der Hüfte, konstante Spannung im Kabel während der gesamten Bewegung, Schulter unten lassen statt hochzuziehen.' where name = 'Kabelzug-Seitheben';
update public.exercises set description = 'Ausführung: An der Maschine mit stabil abgestütztem Oberkörper und angewinkeltem Bein das Polster durch Strecken der Hüfte nach hinten drücken, kontrolliert zurückführen. Ausrüstung: Hüftstrecker-/Gesäßmaschine. Worauf achten: Oberkörper stabil an der Auflage, Bewegung aus der Hüfte statt aus dem unteren Rücken, Gesäß am Endpunkt aktiv anspannen, kein Hohlkreuz.' where name = 'Gesäßmaschine (Hüftstrecker-Maschine)';
update public.exercises set description = 'Ausführung: An der Beinpresse mit nur einem mittig auf der Plattform platzierten Bein die Plattform nach oben drücken, kontrolliert bis zum rechten Winkel im Knie absenken, dann die Seite wechseln. Ausrüstung: Beinpresse. Worauf achten: Knie in Fußrichtung, unterer Rücken bleibt durchgehend an der Lehne, deutlich geringeres Gewicht als beidbeinig wählen, Gesäß nicht von der Sitzfläche abheben.' where name = 'Beinpresse einbeinig';
update public.exercises set description = 'Ausführung: An der Beinpresse mit nahezu gestreckten Beinen nur über die Fußballen auf die Plattform drücken, Fersen maximal anheben, kontrolliert bis zur deutlichen Dehnung absenken. Ausrüstung: Beinpresse. Worauf achten: Beine bleiben nahezu gestreckt ohne die Knie durchzudrücken, volle Bewegungsamplitude nutzen, kein Wippen, Sicherungsarretierung beachten.' where name = 'Wadenheben an der Beinpresse';
update public.exercises set description = 'Ausführung: Mit der Langhantel im Nacken und leicht gebeugten Knien den Oberkörper aus der Hüfte nach vorn beugen, bis eine deutliche Dehnung in der Oberschenkelrückseite spürbar ist, dann über die Hüftstreckung wieder aufrichten. Ausrüstung: Langhantel. Worauf achten: Rücken während der gesamten Bewegung gerade, Knie nur leicht gebeugt, geringes Gewicht wählen und nicht tiefer beugen, als der Rücken gerade bleibt.' where name = 'Good Mornings (Langhantel)';
update public.exercises set description = 'Ausführung: In Rückenlage mit angewinkelten Beinen und Händen locker an den Schläfen abwechselnd den Ellbogen zum gegenüberliegenden Knie führen, während das andere Bein gestreckt bleibt. Ausrüstung: Matte. Worauf achten: Bewegung aus der Bauchmuskulatur einleiten, unteren Rücken am Boden lassen, kontrolliertes Tempo ohne Zug am Nacken mit den Händen.' where name = 'Diagonale Crunches';
update public.exercises set description = 'Ausführung: Liegestütz mit Händen dicht zusammen unter der Brust (Daumen und Zeigefinger bilden eine Raute), Körper kontrolliert absenken, bis die Brust sich der Raute nähert, und wieder nach oben drücken. Ausrüstung: Matte. Worauf achten: Rumpf und Gesäß angespannt, Ellbogen nah am Körper statt nach außen, bei Bedarf auf den Knien ausführen, um das Handgelenk zu entlasten.' where name = 'Diamant-Liegestütz';
update public.exercises set description = 'Ausführung: Aus breiter Liegestützposition mit angespanntem Rumpf den Körper kontrolliert zu einer Seite absenken, während der andere Arm gestreckt zur Seite ausgestreckt bleibt, dann zurück in die Mitte drücken und Seite wechseln. Ausrüstung: Matte. Worauf achten: Rumpf stabil und Becken gerade, kontrolliertes Tempo, bei Bedarf mit den Knien am Boden ausführen.' where name = 'Archer-Liegestütz';
update public.exercises set description = 'Ausführung: In Rückenlage mit gestreckten Armen und Beinen gleichzeitig Oberkörper und Beine kontrolliert anheben, Hände Richtung Füße führen, dann kontrolliert zurück in die Ausgangsposition. Ausrüstung: Matte. Worauf achten: Bewegung aus der Bauchmuskulatur einleiten, unteren Rücken nicht überlasten, bei Beschwerden im unteren Rücken die Beine angewinkelt ausführen.' where name = 'Klappmesser (V-Ups)';
update public.exercises set description = 'Ausführung: Im Sitzen mit leicht angehobenen, angewinkelten Beinen den Oberkörper leicht zurücklehnen und abwechselnd mit den Händen den Boden neben der Hüfte berühren. Ausrüstung: Matte. Worauf achten: Rücken möglichst gerade halten statt rund zu werden, Bewegung aus der Rumpfrotation, kontrolliertes Tempo, bei Bedarf die Füße am Boden lassen, um den unteren Rücken zu entlasten.' where name = 'Russian Twists (ohne Gewicht)';
update public.exercises set description = 'Ausführung: In Rückenlage mit einem aufgestellten Bein das andere Bein strecken und die Hüfte kontrolliert anheben, bis Schultern-Hüfte-Knie eine Linie bilden, kontrolliert absenken. Ausrüstung: Matte. Worauf achten: Becken bleibt gerade und waagerecht, kein Ausweichen zur Seite, Gesäß am oberen Punkt aktiv anspannen, kein Hohlkreuz.' where name = 'Beckenlift einbeinig';
update public.exercises set description = 'Ausführung: Mit dem Rücken flächig an der Wand in die Kniebeuge-Position gehen, bis die Oberschenkel etwa parallel zum Boden sind, Position ruhig statisch halten. Ausrüstung: Wand. Worauf achten: Knie über den Fußgelenken und in Fußrichtung, Rücken durchgehend flächig an der Wand, gleichmäßige Atmung während des Haltens statt die Luft anzuhalten.' where name = 'Wandsitz (Wall Sit)';
update public.exercises set description = 'Ausführung: Im Gehen abwechselnd große, kontrollierte Schritte nach vorn setzen, das hintere Knie Richtung Boden absenken, über die vordere Ferse aufstehen und in den nächsten Schritt übergehen. Ausrüstung: keine. Worauf achten: Oberkörper aufrecht, vorderes Knie bleibt über dem Fuß und fällt nicht nach innen, kontrolliertes Tempo, Rumpf stabil halten.' where name = 'Ausfallschritte im Gehen (ohne Gewicht)';
update public.exercises set description = 'Ausführung: Im hüftbreiten Stand mit leicht nach außen gedrehten Füßen das Gesäß nach hinten-unten absenken, bis die Oberschenkel etwa parallel zum Boden sind, dann über die Fersen wieder aufstehen. Ausrüstung: keine. Worauf achten: Knie in Fußrichtung und fallen nicht nach innen, Rücken gerade, Gewicht auf der gesamten Fußsohle statt auf den Zehenspitzen.' where name = 'Kniebeuge (Bodyweight)';
update public.exercises set description = 'Ausführung: Im Sitzen mit hinter dem Körper aufgestützten Händen oder Unterarmen die Hüfte kontrolliert anheben, bis der Körper eine gerade Linie bildet, Position ruhig halten. Ausrüstung: Matte. Worauf achten: Gesäß aktiv anspannen, Schultern über den Stützpunkten, gleichmäßige Atmung, Kopf in Verlängerung der Wirbelsäule lassen.' where name = 'Reverse Plank (Unterarmstütz rückwärts)';
update public.exercises set description = 'Ausführung: Im Unterarm-Seitstütz mit Ellbogen unter der Schulter die Hüfte kontrolliert Richtung Boden absenken und wieder anheben, ohne den Boden zu berühren. Ausrüstung: Matte. Worauf achten: Körper bleibt in einer Linie, kein Vor- oder Zurückkippen, Bewegung kommt aus der seitlichen Rumpfmuskulatur, kontrolliertes Tempo.' where name = 'Seitstütz mit Hüftheben (Side Plank Hip Dips)';
update public.exercises set description = 'Ausführung: In der Beckenlift-Position mit angespanntem Gesäß die Hüfte oben halten und abwechselnd ein Knie kontrolliert zur Brust heranziehen, ohne die Hüfte absinken zu lassen. Ausrüstung: Matte. Worauf achten: Becken bleibt während des gesamten Übungsablaufs stabil und gerade, Gesäß durchgehend angespannt, kein Ausweichen zur Seite.' where name = 'Beckenlift mit Beinheben (Glute Bridge March)';
update public.exercises set description = 'Ausführung: Während der Abwärtsbewegung eines Liegestützes ein Knie seitlich Richtung gleichseitigen Ellbogen ziehen, dann wieder strecken und nach oben drücken, Seite wechseln. Ausrüstung: Matte. Worauf achten: Rumpf stabil und Becken gerade, Bewegung kontrolliert ohne Schwung, bei Bedarf auf den Knien ausführen.' where name = 'Spiderman-Liegestütz';
update public.exercises set description = 'Ausführung: Aus dem umgekehrten V (Hüfte hoch, Hände und Füße am Boden) den Oberkörper kontrolliert absenken, bis sich der Kopf dem Boden annähert, dann wieder kraftvoll nach oben drücken. Ausrüstung: Matte. Worauf achten: Hüfte bleibt während der gesamten Bewegung hoch, Bewegung wie ein vertikaler Liegestütz, Blick leicht nach hinten zwischen die Hände, Kopf kontrolliert statt mit Schwung absenken.' where name = 'Pike Push-Up (Schulterliegestütz)';
update public.exercises set description = 'Ausführung: Mit schulterbreitem Untergriff (Handflächen zum Gesicht) an der Stange hängend den Körper durch Zug der Rückenmuskulatur nach oben ziehen, bis das Kinn über der Stange ist, kontrolliert bis zur fast vollen Armstreckung absenken. Ausrüstung: Klimmzugstange. Worauf achten: Schultern aktiv nach unten ziehen, kein Schwung, volle Bewegungsamplitude nutzen, Rumpf stabil halten.' where name = 'Klimmzug im Untergriff (Chin-Up)';
update public.exercises set description = 'Ausführung: Unter einer tief hängenden Stange oder an Ringen mit gestrecktem, angespanntem Körper den Oberkörper zur Stange hochziehen, Schulterblätter zusammenziehen, kontrolliert bis zur fast vollen Armstreckung absenken. Ausrüstung: Klimmzugstange (tief) oder Ringe/Schlaufen. Worauf achten: Körper bleibt durchgehend in einer geraden Linie, Ferse aufgesetzt, Schwierigkeitsgrad über den Körperwinkel steuern, Gesäß nicht durchhängen lassen.' where name = 'Australische Klimmzüge (Inverted Row)';
update public.exercises set description = 'Ausführung: Auf einer Erhöhung stehend das freie Bein langsam kontrolliert nach vorn-unten absenken, bis die Ferse fast den Boden berührt, dann über das Standbein zurück nach oben drücken. Ausrüstung: Stufe oder stabile Erhöhung. Worauf achten: Bewegung sehr langsam und kontrolliert, Knie des Standbeins bleibt in Fußrichtung und fällt nicht nach innen, Standbein trägt die gesamte Kontrolle.' where name = 'Step-Down (exzentrisches Beintraining)';
update public.exercises set description = 'Ausführung: Mit einem Bein diagonal hinter das Standbein kreuzen und das hintere Knie kontrolliert Richtung Boden absenken, dann über das vordere Bein zurück in den Stand drücken. Ausrüstung: keine. Worauf achten: Oberkörper aufrecht, Knie des vorderen Beins bleibt stabil über dem Fuß, kontrolliertes Tempo, auf sicheren Halt beim Kreuzschritt achten.' where name = 'Curtsy Lunge (Reverenz-Ausfallschritt)';
update public.exercises set description = 'Ausführung: In Rückenlage mit den Händen locker neben dem Körper die gestreckten Beine gemeinsam anheben, bis sie senkrecht stehen, kontrolliert wieder absenken, ohne den unteren Rücken vom Boden abzuheben. Ausrüstung: Matte. Worauf achten: Unterer Rücken bleibt durchgehend am Boden, Bewegung kontrolliert ohne Schwung, bei Beschwerden im unteren Rücken die Beine leicht angewinkelt ausführen.' where name = 'Beinheben liegend (Lying Leg Raise)';
update public.exercises set description = 'Ausführung: In Seitlage mit gestrecktem Körper und leicht abgestütztem Kopf das obere Bein kontrolliert anheben und wieder absenken, ohne dass das Becken nach hinten kippt. Ausrüstung: Matte. Worauf achten: Rumpf stabil, Bewegung isoliert aus der Hüfte, kontrolliertes Tempo ohne Schwung, Fußspitze zeigt nach vorn statt nach oben.' where name = 'Seitliches Beinheben im Liegen';
update public.exercises set description = 'Ausführung: Im hohen Stütz (Liegestützposition) mit angespanntem Rumpf abwechselnd mit einer Hand die gegenüberliegende Schulter berühren, ohne das Becken zu verdrehen. Ausrüstung: Matte. Worauf achten: Becken bleibt ruhig und gerade, Füße etwas breiter stellen für mehr Stabilität, kontrolliertes Tempo statt schnellem Tempo mit Ausweichbewegung.' where name = 'Unterarmstütz mit Schulterklopfen (Plank Shoulder Taps)';
update public.exercises set description = 'Ausführung: Im aufrechten Stand die Schultern großzügig und langsam nach vorn und anschließend nach hinten kreisen lassen. Ausrüstung: keine. Worauf achten: Bewegung groß und langsam ausführen, Arme locker hängen lassen, Atmung ruhig und gleichmäßig.' where name = 'Schulterkreisen';
update public.exercises set description = 'Ausführung: Im Sitzen mit aufrechtem Oberkörper den Kopf sanft zur Seite neigen, bis eine leichte Dehnung im seitlichen Nacken spürbar ist, Position ca. 20-30 Sekunden ruhig halten, Seite wechseln. Ausrüstung: keine, ggf. Stuhl. Worauf achten: Bewegung sehr sanft und ohne Ziehen mit der Hand am Kopf, gleichmäßige Atmung, Schulter der gedehnten Seite bewusst unten lassen.' where name = 'Nackendehnung im Sitzen';
update public.exercises set description = 'Ausführung: Unterarm im rechten Winkel an den Türrahmen anlegen und den Oberkörper leicht nach vorn drehen, bis eine deutliche, aber angenehme Dehnung in der Brust spürbar ist, Position ca. 20-30 Sekunden halten, Seite wechseln. Ausrüstung: Türrahmen. Worauf achten: Dehnung sanft aufbauen, keine ruckartigen Bewegungen, gleichmäßige Atmung, Schulter nicht hochziehen.' where name = 'Brustdehnung im Türrahmen';
update public.exercises set description = 'Ausführung: An einer Stange oder einem festen Halt mit gestreckten Armen hängen bzw. das Becken nach hinten absenken, bis eine deutliche Dehnung im seitlichen Rücken spürbar ist, Position ca. 20-30 Sekunden halten. Ausrüstung: Klimmzugstange oder fester Halt. Worauf achten: Schultern entspannt, Dehnung langsam aufbauen statt ruckartig, gleichmäßige Atmung, bei Handgelenkbeschwerden Griff anpassen.' where name = 'Latissimus-Dehnung an der Stange';
update public.exercises set description = 'Ausführung: Im tiefen Ausfallschritt mit aufgestelltem hinteren Knie das Becken kontrolliert nach vorn-unten schieben, bis eine deutliche Dehnung in der Hüftvorderseite des hinteren Beins spürbar ist, Position ca. 20-30 Sekunden halten, Seite wechseln. Ausrüstung: Matte. Worauf achten: Oberkörper aufrecht, Becken nicht zur Seite kippen, sanft und ohne Wippen in die Dehnung gehen.' where name = 'Hüftbeuger-Dehnung im Ausfallschritt';
update public.exercises set description = 'Ausführung: Mit gestrecktem hinteren Bein und durchgehend aufgesetzter Ferse gegen eine Wand lehnen, bis eine deutliche Dehnung in der Wade spürbar ist, Position ca. 20-30 Sekunden halten, Seite wechseln. Ausrüstung: Wand. Worauf achten: Ferse bleibt am Boden, Fuß zeigt gerade nach vorn, Dehnung langsam aufbauen statt federnd zu wippen.' where name = 'Wadendehnung an der Wand';
update public.exercises set description = 'Ausführung: In Rückenlage einen Knöchel auf das gegenüberliegende Knie legen und das freie Bein mit beiden Händen zur Brust heranziehen, bis eine deutliche Dehnung im Gesäß spürbar ist, Position ca. 20-30 Sekunden halten, Seite wechseln. Ausrüstung: Matte. Worauf achten: Unterer Rücken bleibt am Boden, Dehnung sanft aufbauen statt zu ziehen, gleichmäßige Atmung.' where name = 'Piriformis-Dehnung (Figure-4)';
update public.exercises set description = 'Ausführung: Im Sitzen mit aufrechtem Oberkörper die Fußsohlen zusammenführen und die Knie sanft mit den Ellbogen Richtung Boden drücken, Position ca. 20-30 Sekunden halten. Ausrüstung: Matte. Worauf achten: Rücken gerade halten statt rund zu werden, Dehnung langsam und ohne Wippen aufbauen.' where name = 'Schmetterlingsdehnung';
update public.exercises set description = 'Ausführung: Im hüftbreiten Stand mit leicht gebeugten Knien den Oberkörper locker und kontrolliert von einer Seite zur anderen rotieren lassen, Arme schwingen dabei entspannt mit. Ausrüstung: keine. Worauf achten: Hüfte bleibt stabil nach vorn ausgerichtet, Bewegung kommt aus der Brustwirbelsäule, keine ruckartigen Bewegungen.' where name = 'Rumpfrotation im Stehen';
update public.exercises set description = 'Ausführung: Aus dem Fersensitz die Arme nach vorn ausstrecken und den Oberkörper entspannt Richtung Boden absenken, Position ca. 30-60 Sekunden halten. Ausrüstung: Matte. Worauf achten: Gesäß bleibt auf oder nah an den Fersen, Atmung tief und ruhig in den Rücken, bei Knie- oder Knöchelbeschwerden ein Kissen unterlegen.' where name = 'Kindhaltung (Child''s Pose)';
update public.exercises set description = 'Ausführung: Im Vierfüßlerstand einen Arm unter dem Körper hindurchführen, bis Schulter und Kopf den Boden berühren, dann kontrolliert zurückrotieren und den gleichen Arm zur Decke strecken, Blick folgt der Hand. Ausrüstung: Matte. Worauf achten: Hüfte bleibt ruhig und stabil, Bewegung kommt aus der Brustwirbelsäule, langsames Tempo ohne Schwung.' where name = 'Thread the Needle (dynamische BWS-Rotation)';
update public.exercises set description = 'Ausführung: Im hohen Kniestand mit einem aufgestellten Bein und stabilem Oberkörper das Becken kontrolliert kreisen lassen bzw. seitlich verlagern, um die Hüfte zu öffnen. Ausrüstung: Matte. Worauf achten: Oberkörper aufrecht, Bewegung ruhig und im schmerzfreien Bereich, Knie am Boden ggf. mit Matte polstern.' where name = 'Hüftöffner im Kniestand';
update public.exercises set description = 'Ausführung: Einen Stab oder ein Handtuch mit beiden Händen breit greifen und mit gestreckten Armen über den Kopf nach hinten führen, so weit es die Beweglichkeit schmerzfrei zulässt, dann kontrolliert zurück nach vorn. Ausrüstung: Stab, Besenstiel oder Handtuch. Worauf achten: Griffbreite so wählen, dass die Bewegung schmerzfrei bleibt, langsames Tempo, Griffbreite bei Bedarf vergrößern statt die Schulter zu forcieren.' where name = 'Schultermobilisation mit dem Stab';
update public.exercises set description = 'Ausführung: Die Handgelenke abwechselnd langsam kreisen lassen sowie die Hände bei gestreckten Armen kontrolliert nach oben und unten abknicken. Ausrüstung: keine. Worauf achten: Bewegung langsam und im schmerzfreien Bereich, keine ruckartigen Bewegungen, bei Beschwerden die Amplitude reduzieren.' where name = 'Handgelenk-Mobilisation';
update public.exercises set description = 'Ausführung: Im Sitzen oder Stehen die Füße abwechselnd langsam kreisen lassen sowie die Zehenspitzen abwechselnd Richtung Schienbein ziehen und wieder strecken. Ausrüstung: keine. Worauf achten: Bewegung kontrolliert durch den vollen, schmerzfreien Bewegungsradius führen, im Stehen ggf. an einer Wand festhalten.' where name = 'Knöchelmobilisation';
update public.exercises set description = 'Ausführung: Im Vierfüßlerstand mit stabilem Becken eine Hand hinter den Kopf legen und den Ellbogen kontrolliert Richtung Decke rotieren, Blick folgt dem Ellbogen, dann zurück und Seite wechseln. Ausrüstung: Matte. Worauf achten: Hüfte bleibt ruhig, Bewegung kommt ausschließlich aus der Brustwirbelsäule, langsames Tempo ohne Schwung.' where name = 'Thorakale Rotation im Vierfüßlerstand';
update public.exercises set description = 'Ausführung: Mit sicherem Festhalten an einer Wand oder Stange ein Bein locker und kontrolliert seitlich vor dem Körper hin- und herschwingen lassen, Seite wechseln. Ausrüstung: Wand oder Stange zum Festhalten. Worauf achten: Oberkörper stabil, Bewegung aus der Hüfte statt aus dem Rumpf, Amplitude langsam steigern statt von Beginn an maximal auszuschwingen.' where name = 'Beinschwünge seitlich';
update public.exercises set description = 'Ausführung: Im Vierfüßlerstand die Knie breit auseinander positionieren und das Becken langsam nach hinten Richtung Fersen schieben, bis eine deutliche Dehnung in der Leiste spürbar ist, Position ca. 20-30 Sekunden halten. Ausrüstung: Matte. Worauf achten: Dehnung langsam aufbauen, im schmerzfreien Bereich bleiben, gleichmäßige Atmung, Knie bei Bedarf mit Matte polstern.' where name = 'Frosch-Dehnung';
update public.exercises set description = 'Ausführung: In Bauchlage die Hände unter den Schultern aufsetzen und den Oberkörper langsam bis zur angenehmen Dehnung nach oben drücken, Becken bleibt am Boden, Position ca. 20-30 Sekunden halten. Ausrüstung: Matte. Worauf achten: Bewegung langsam aufbauen, kein Schmerz im unteren Rücken, Schultern entspannt und von den Ohren weg.' where name = 'Kobra-Dehnung';
update public.exercises set description = 'Ausführung: Im Stand mit leicht gebeugten Knien den Oberkörper langsam und locker nach vorn hängen lassen, Arme und Kopf hängen entspannt, Position ca. 20-30 Sekunden halten. Ausrüstung: keine. Worauf achten: Dehnung passiv wirken lassen statt zu federn, Knie bei Bedarf stärker beugen, langsam wieder aufrichten, um Schwindel zu vermeiden.' where name = 'Vorbeuge im Stehen';
update public.exercises set description = 'Ausführung: Im aufrechten Stand beide Arme mit maximaler, schmerzfreier Reichweite große Kreise nach vorn und anschließend nach hinten ziehen lassen. Ausrüstung: keine. Worauf achten: Bewegung groß und kontrolliert statt hektisch, Rumpf bleibt stabil, ausreichend Platz um sich herum einplanen.' where name = 'Große Armkreise';
update public.exercises set description = 'Ausführung: Mit der Faszienrolle unter dem oberen Rücken liegend und Händen hinter dem Kopf verschränkt langsam vor- und zurückrollen, an Verspannungspunkten kurz verweilen. Ausrüstung: Faszienrolle. Worauf achten: Nacken entspannt, Bauch leicht angespannt, Bewegung langsam, unteren Rücken (Lendenwirbelsäule) konsequent aussparen.' where name = 'Faszienrolle Rücken';
update public.exercises set description = 'Ausführung: Mit der Faszienrolle unter dem Oberschenkel liegend bzw. auf den Armen abgestützt langsam vor- und zurückrollen, an Verspannungspunkten kurz verweilen. Ausrüstung: Faszienrolle. Worauf achten: Bewegung langsam, Rumpf stabil, Druck über die Armstützung dosieren, Kniegelenk selbst nicht direkt beplanken.' where name = 'Faszienrolle Oberschenkel';
update public.exercises set description = 'Ausführung: Auf dem Air Bike mit aufrechter Haltung gleichzeitig in die Pedale treten und die Arme aktiv mitbewegen, Intensität schrittweise über das Tempo steuern. Ausrüstung: Assault Bike/Air Bike. Worauf achten: Aufrechte Haltung, gleichmäßiger Rhythmus zwischen Armen und Beinen, Intensität über Herzfrequenz oder Tempo steuern, ausreichend Aufwärmen vor hoher Intensität.' where name = 'Assault Bike (Air Bike)';
update public.exercises set description = 'Ausführung: Mit dem Springseil in gleichmäßigem Rhythmus über die Fußballen mit nur geringer Sprunghöhe springen, die Handgelenke drehen das Seil. Ausrüstung: Springseil, ggf. dämpfender Untergrund. Worauf achten: Weiche, geräuscharme Landung über die Fußballen, Ellbogen nah am Körper, aufrechte Haltung, Knie leicht gebeugt zur Stoßdämpfung.' where name = 'Seilspringen (Jump Rope)';
update public.exercises set description = 'Ausführung: Den beladenen Schlitten mit gestreckten oder leicht gebeugten Armen vor dem Körper über eine festgelegte Strecke schieben, Oberkörper dabei leicht nach vorn geneigt. Ausrüstung: Sled/Schlitten mit Gewicht. Worauf achten: Rücken gerade, Antrieb aus den Beinen statt aus dem Rücken, kurze kraftvolle Schritte, moderates Gewicht bei ungewohnter Belastung wählen.' where name = 'Schlittenschieben (Sled Push)';
update public.exercises set description = 'Ausführung: Den beladenen Schlitten über ein Seil oder einen Gurt mit gleichmäßigen Schritten rückwärts oder vorwärts ziehend über eine festgelegte Strecke bewegen. Ausrüstung: Sled/Schlitten mit Gewicht, Seil oder Zuggurt. Worauf achten: Rücken gerade, gleichmäßiges Tempo, Rumpf stabil, beim Rückwärtsgehen auf freie Strecke achten.' where name = 'Schlittenziehen (Sled Pull)';
update public.exercises set description = 'Ausführung: Kurze Hochintensitätsphase bei einer frei wählbaren Übung (z. B. Burpees, Mountain Climbers), gefolgt von einer kurzen Erholungsphase, über mehrere Runden im festen Wechsel wiederholen. Ausrüstung: je nach gewählter Übung. Worauf achten: Technik auch bei hoher Intensität sauber halten statt sie für Tempo zu opfern, Belastung an die eigene Fitness anpassen, ausreichend Aufwärmen vor der ersten Runde.' where name = 'Tabata-Intervalle (20/10, freie Übungsauswahl)';
update public.exercises set description = 'Ausführung: Im lockeren, hüftbreiten Stand Schlagkombinationen (Jab, Cross, Haken) mit Armen und Rumpfrotation kontrolliert gegen den Sandsack ausführen. Ausrüstung: Sandsack, Boxhandschuhe/Bandagen. Worauf achten: Handgelenke stabil halten und beim Treffer nicht abknicken, Rotation aus der Hüfte, lockere Beinarbeit, Bandagen/Handschuhe zum Schutz der Handgelenke verwenden.' where name = 'Boxen am Sandsack';
update public.exercises set description = 'Ausführung: Seitliche, kontrollierte Sprünge von einem Bein auf das andere, das hintere Bein schwingt dabei hinter dem Standbein her, im Rhythmus die Seite wechseln. Ausrüstung: keine, rutschfester Untergrund. Worauf achten: Weiche Landung über den Fußballen, Knie leicht gebeugt und in Fußrichtung, Rumpf stabil.' where name = 'Skaters (seitliche Sprünge)';
update public.exercises set description = 'Ausführung: Aus der Kniebeuge-Position mit hüftbreitem Stand explosiv nach oben abspringen, weich über die Fußballen mit gebeugten Knien landen und kontrolliert in die nächste Kniebeuge übergehen. Ausrüstung: keine. Worauf achten: Weiche Landung mit gebeugten Knien, Knie fallen dabei nicht nach innen, Rumpf stabil, Rhythmus an die eigene Fitness anpassen.' where name = 'Squat Jumps (Kniebeugensprünge)';
update public.exercises set description = 'Ausführung: Aus dem hüftbreiten Stand explosiv nach oben springen und dabei beide Knie zur Brust anziehen, weich über die Fußballen mit gebeugten Knien landen. Ausrüstung: keine. Worauf achten: Weiche Landung, Rumpf stabil, ausreichend Platz nach oben und zur Seite einplanen, Sprunghöhe an die eigene Landekontrolle anpassen.' where name = 'Tuck Jumps (Strecksprünge mit Knieanzug)';
update public.exercises set description = 'Ausführung: Freie Schlagkombinationen mit aktiver Beinarbeit und Rumpfrotation ohne Gerät oder Partner ausführen, kontinuierlich in Bewegung bleiben. Ausrüstung: keine. Worauf achten: Lockere, kontrollierte Bewegungen ohne die Arme komplett durchzustrecken, gleichmäßiger Rhythmus, aufrechte Grundhaltung.' where name = 'Schattenboxen (Shadow Boxing)';
update public.exercises set description = 'Ausführung: Zügiges, kontrolliertes Treppauf- und -absteigen über mehrere Stockwerke oder eine Treppenstrecke, Tempo an die eigene Fitness anpassen. Ausrüstung: Treppe, festes Schuhwerk. Worauf achten: Fuß vollständig auf der Stufe aufsetzen, Geländer nur zur Sicherheit nutzen, beim Abstieg besonders auf sicheren Tritt achten, da hier das Sturzrisiko höher ist.' where name = 'Treppenlaufen (reale Treppe)';
update public.exercises set description = 'Ausführung: Zügiges Gehen im Freien mit selbst gewählten, wechselnden Tempo-Phasen, aktiver Armeinsatz. Ausrüstung: keine, festes Schuhwerk. Worauf achten: Aufrechte Haltung, gleichmäßiger Atemrhythmus, Untergrund und Wetter berücksichtigen, Tempo bei unebenem Boden reduzieren.' where name = 'Walking-Intervalle im Freien';
update public.exercises set description = 'Ausführung: Kontinuierliches Bahnenziehen in einem Schwimmstil der Wahl (z. B. Kraul, Brust) mit sauberer Wasserlage, Tempo und Distanz an die eigene Fitness anpassen. Ausrüstung: Schwimmbad. Worauf achten: Gleichmäßige Atmung, saubere Technik vor Tempo, ausreichend Aufwärmen mit lockeren Bahnen zu Beginn.' where name = 'Schwimmen (Bahnenziehen)';
update public.exercises set description = 'Ausführung: Freies, rhythmisches Bewegen zu Musik mit kontinuierlichem, fließendem Einsatz von Armen und Beinen, Intensität über Tempo und Bewegungsumfang steuern. Ausrüstung: keine, ggf. Musik. Worauf achten: Gelenkschonende, fließende Bewegungen ohne abrupte Richtungswechsel, ausreichend Platz und rutschfesten Boden einplanen.' where name = 'Tanz-Cardio (freies Rhythmustraining)';
update public.exercises set description = 'Ausführung: Auf dem Spinning-Rad mit korrekt eingestellter Sitzposition im Sitzen oder Wiegetritt mit wechselnder Intensität und Widerstand fahren. Ausrüstung: Spinning-/Indoor-Cycling-Rad. Worauf achten: Sattel- und Lenkerhöhe vor dem Start korrekt einstellen, gleichmäßige Trittfrequenz, Widerstand schrittweise statt sprunghaft steigern.' where name = 'Indoor Cycling / Spinning (hohe Intensität)';
update public.exercises set description = 'Ausführung: Den Medizinball mit gestreckten Armen über den Kopf heben und mit kontrollierter Kraft aus der Hüfte auf den Boden schleudern, dann kontrolliert aufheben und wiederholen. Ausrüstung: Medizinball (wallfest). Worauf achten: Rumpf angespannt, Bewegung aus der Hüfte und den Schultern, Knie beim Aufheben leicht beugen statt mit rundem Rücken zu bücken.' where name = 'Medizinball-Slams';
update public.exercises set description = 'Ausführung: Am Rudergerät mit fest angeschnalltem Fuß im gleichmäßigen Tempo über eine längere Distanz rudern, Beine-Rücken-Arme-Sequenz konstant halten. Ausrüstung: Rudergerät. Worauf achten: Bewegungsreihenfolge Beine-Rücken-Arme einhalten, aufrechter Oberkörper, gleichmäßiges Tempo statt Sprints, Rücken beim Zug nicht runden.' where name = 'Rudergerät (Dauerbelastung)';
update public.exercises set description = 'Ausführung: Auf der Stelle mit hoher Frequenz die Knie abwechselnd bis über Hüfthöhe anheben, aktiver, gegenläufiger Armeinsatz. Ausrüstung: keine, rutschfester Untergrund. Worauf achten: Aufrechte Haltung, Landung weich über den Fußballen, hohe Frequenz statt große Schritte, Rumpf stabil halten.' where name = 'High Knees (schnelles Kniehebellauf auf der Stelle)';
update public.exercises set description = 'Ausführung: Im Unterarmstütz mit angespanntem Rumpf die Beine mit einem kleinen, kontrollierten Sprung auseinander und wieder zusammenführen. Ausrüstung: Matte. Worauf achten: Becken bleibt ruhig und auf einer Höhe, kein Durchhängen oder Aufstellen der Hüfte, kontrollierte Landung, Tempo an die eigene Fitness anpassen.' where name = 'Plank Jacks (Unterarmstütz mit Beinsprung)';
update public.exercises set description = 'Ausführung: Auf dem Laufband im Wechsel kurze Sprintphasen mit hoher Geschwindigkeit und längere Erholungsphasen im Gehen oder lockeren Laufen kombinieren, Geschwindigkeit dabei stets kontrolliert anpassen. Ausrüstung: Laufband. Worauf achten: Geschwindigkeit schrittweise steigern statt abrupt hochzuschalten, sichere Handhabung der Konsole während des Tempowechsels, ausreichend Aufwärmen vor dem ersten Sprint, Seitenholme im Notfall nutzen.' where name = 'Laufband-Sprintintervalle (Tempowechsel)';

-- Verifikation: sollte 0 Zeilen liefern (keine Trainings-Variablen mehr im Text).
select name, description
from public.exercises
where description ~* '\ysätze\y|\ywiederholung|\ywdh\.?\y|\yrpe\y|%\s*1\s*rm|\y1rm\y';

-- Verifikation: sollte 204 liefern.
select count(*) as anzahl_uebungen from public.exercises;
