-- ============================================================================
-- Dream And Do It – Kundenplattform
-- Runde 22 (Nachtrag 5): Kurse in der Übungsbibliothek
--
-- Kursformate (Gruppen-/Online-Kurse) werden als Einheiten in der Übungsbibliothek
-- geführt – bewusst in den BESTEHENDEN Kategorien, ohne neue Spalte:
--   Mobilisation: Yoga, Pilates, Rückenfit, Faszientraining, Stretching, Tai Chi
--   Cardio:       Spinning, Zumba, Aqua-Fitness, Step-Aerobic, Lauftreff, Cardio-Box
--   Bodyweight:   HIIT/Tabata, Bootcamp/Zirkel, Bauch-Beine-Po
--   Kraft:        Bodypump, Functional/Kettlebell, Kraftzirkel
-- Erkennungsmerkmal: Der Name beginnt mit "Kurs: ". Die Plattform behandelt solche
-- Übungen automatisch als Dauer-Einheit (Minuten) – in der Plan-Erstellung, beim
-- Loggen im Training und in der Auswertung (Ausdauer-/Kurszeit im Bericht).
--
-- Idempotent: bereits vorhandene Namen werden nicht erneut angelegt.
-- Im Supabase SQL Editor ausführen, NACHDEM 001-058 bereits liefen.
-- ============================================================================

with data(name, muscle_group, description, category, movement_pattern) as (values
  ('Kurs: Yoga (Hatha/Vinyasa)', 'Ganzkörper, Beweglichkeit, Rumpf', 'Kursformat (Gruppen- oder Online-Kurs) – beim Loggen die tatsächliche Dauer in Minuten angeben. Ausführung: Geleitete Abfolge aus Körperhaltungen (Asanas), Atemführung und kurzer Entspannung; die Haltungen werden ruhig gehalten oder im Atemfluss verbunden. Ausrüstung: Yogamatte, bequeme Kleidung, optional Block und Gurt. Worauf achten: Nur so weit in die Haltungen gehen, wie sie ohne Schmerz und ohne Atemanhalten möglich sind; bei Schwangerschaft, Bluthochdruck oder akuten Beschwerden vorher Rücksprache mit Trainer/Arzt halten. Dauer: 60–90 Minuten.', 'Mobilisation', 'sonstige'),
  ('Kurs: Pilates', 'Rumpf, Beckenboden, Gesäß, Haltung', 'Kursformat (Gruppen- oder Online-Kurs) – beim Loggen die tatsächliche Dauer in Minuten angeben. Ausführung: Kontrollierte, langsame Übungen aus der Körpermitte (Powerhouse) mit koordinierter Atmung, überwiegend auf der Matte. Ausrüstung: Matte, optional Kleingeräte (Pilates-Ring, Ball, Band). Worauf achten: Qualität vor Wiederholungszahl; Rippenbogen und Becken stabil halten, kein Hohlkreuz, bei Rücken- oder Nackenbeschwerden die Anweisungen der Kursleitung zur Anpassung nutzen. Dauer: 45–60 Minuten.', 'Mobilisation', 'sonstige'),
  ('Kurs: Rückenfit (Rückenschule)', 'Rückenstrecker, Rumpf, Schulter', 'Kursformat (Gruppen- oder Online-Kurs) – beim Loggen die tatsächliche Dauer in Minuten angeben. Ausführung: Gruppenkurs mit Mobilisation, Kräftigung der Rumpf- und Rückenmuskulatur sowie Haltungsschulung für den Alltag. Ausrüstung: Matte, ggf. Band oder Kleinhantel. Worauf achten: Schmerzfreier Bewegungsradius, ruhige Atmung, bei akuten Rückenschmerzen oder Bandscheibenvorfall vorab ärztlich/therapeutisch abklären. Dauer: 45–60 Minuten.', 'Mobilisation', 'rumpf_hinten'),
  ('Kurs: Faszientraining', 'Ganzkörper, Faszien', 'Kursformat (Gruppen- oder Online-Kurs) – beim Loggen die tatsächliche Dauer in Minuten angeben. Ausführung: Gruppenkurs mit Faszienrolle und Ball (Selbstmassage) sowie dynamischen Dehn- und Federbewegungen für das Bindegewebe. Ausrüstung: Faszienrolle, Faszienball, Matte. Worauf achten: Druck dosieren (angenehm-intensiv, nicht schmerzhaft), nicht direkt auf Gelenke oder die Lendenwirbelsäule rollen, langsam rollen und gleichmäßig weiteratmen. Dauer: 45–60 Minuten.', 'Mobilisation', 'sonstige'),
  ('Kurs: Stretching & Mobility', 'Ganzkörper, Beweglichkeit', 'Kursformat (Gruppen- oder Online-Kurs) – beim Loggen die tatsächliche Dauer in Minuten angeben. Ausführung: Gruppenkurs mit Dehn- und Mobilisationsübungen für die großen Gelenke und Muskelketten, häufig als Ausgleich zu Kraft- und Ausdauertraining. Ausrüstung: Matte. Worauf achten: Dehnungen ohne Wippen und ohne Schmerz halten, ruhig atmen, Gelenke nicht in Endstellung überlasten. Dauer: 30–45 Minuten.', 'Mobilisation', 'sonstige'),
  ('Kurs: Tai Chi / Qigong', 'Ganzkörper, Gleichgewicht, Rumpf', 'Kursformat (Gruppen- oder Online-Kurs) – beim Loggen die tatsächliche Dauer in Minuten angeben. Ausführung: Langsame, fließende Bewegungsfolgen mit Atemführung und Gewichtsverlagerung; trainiert Gleichgewicht, Koordination und Entspannung. Ausrüstung: Bequeme Kleidung, rutschfeste Schuhe oder barfuß. Worauf achten: Knie nicht überstrecken, Gewicht bewusst verlagern, ruhig und ohne Hast bewegen; ideal auch zur Sturzprophylaxe. Dauer: 45–60 Minuten.', 'Mobilisation', 'sonstige'),
  ('Kurs: Spinning / Indoor Cycling', 'Beine, Herz-Kreislauf', 'Kursformat (Gruppen- oder Online-Kurs) – beim Loggen die tatsächliche Dauer in Minuten angeben. Ausführung: Musikgeführtes Gruppentraining auf dem Indoor-Bike mit Intervallen, Bergfahrten und Sprints nach Anleitung der Kursleitung. Ausrüstung: Spinning-Bike, Trinkflasche, Handtuch, ggf. Radschuhe. Worauf achten: Sattel- und Lenkerhöhe vorher korrekt einstellen, Widerstand so wählen, dass die Trittfrequenz kontrolliert bleibt, Rücken gerade, ausreichend trinken. Dauer: 45–60 Minuten.', 'Cardio', 'sonstige'),
  ('Kurs: Zumba / Dance Fitness', 'Ganzkörper, Herz-Kreislauf', 'Kursformat (Gruppen- oder Online-Kurs) – beim Loggen die tatsächliche Dauer in Minuten angeben. Ausführung: Choreografierte Tanzschritte zu Musik – abwechselnd intensive und ruhigere Passagen für Ausdauer, Koordination und Spaß an der Bewegung. Ausrüstung: Bequeme Sportkleidung, Hallenschuhe mit guter Dämpfung. Worauf achten: Sprünge und Drehungen dem eigenen Niveau anpassen, Knie in Fußrichtung, Pausen bei Bedarf, ausreichend trinken. Dauer: 45–60 Minuten.', 'Cardio', 'sonstige'),
  ('Kurs: Aqua-Fitness', 'Ganzkörper, Herz-Kreislauf, Gelenke', 'Kursformat (Gruppen- oder Online-Kurs) – beim Loggen die tatsächliche Dauer in Minuten angeben. Ausführung: Gruppentraining im brusthohen Wasser mit Laufen, Hüpfen und Widerstandsübungen; der Auftrieb entlastet Gelenke und Wirbelsäule. Ausrüstung: Badebekleidung, Handtuch, ggf. Wasserhanteln oder Poolnudel. Worauf achten: Zum Kurs ausreichend trinken (auch im Wasser wird geschwitzt), rutschfeste Badeschuhe nutzen, Bewegungen gegen den Wasserwiderstand kontrolliert ausführen. Dauer: 45–60 Minuten.', 'Cardio', 'sonstige'),
  ('Kurs: Step-Aerobic', 'Beine, Gesäß, Herz-Kreislauf', 'Kursformat (Gruppen- oder Online-Kurs) – beim Loggen die tatsächliche Dauer in Minuten angeben. Ausführung: Choreografierte Schrittfolgen auf und neben dem Stepper zu Musik – fördert Ausdauer, Koordination und Beinmuskulatur. Ausrüstung: Stepper in passender Höhe, Hallenschuhe. Worauf achten: Beim Aufsteigen den ganzen Fuß aufsetzen, nicht rückwärts vom Step springen, Stephöhe dem Niveau anpassen, Knie nicht durchstrecken. Dauer: 45–60 Minuten.', 'Cardio', 'sonstige'),
  ('Kurs: Lauftreff / Lauf-Gruppe', 'Beine, Herz-Kreislauf', 'Kursformat (Gruppen- oder Online-Kurs) – beim Loggen die tatsächliche Dauer in Minuten angeben. Ausführung: Gemeinsames Ausdauerlaufen in der Gruppe im lockeren, gesprächsfähigen Tempo, bei Bedarf mit Intervallen oder Lauf-ABC. Ausrüstung: Laufschuhe, wetterangepasste Kleidung, ggf. Trinkflasche. Worauf achten: Tempo so wählen, dass du dich dabei noch unterhalten kannst; langsam einlaufen und auslaufen, bei Schmerzen im Knie oder Schienbein pausieren. Dauer: 40–60 Minuten.', 'Cardio', 'sonstige'),
  ('Kurs: Cardio-Box / Kickbox-Fitness', 'Ganzkörper, Schulter, Rumpf, Herz-Kreislauf', 'Kursformat (Gruppen- oder Online-Kurs) – beim Loggen die tatsächliche Dauer in Minuten angeben. Ausführung: Gruppenkurs mit Schlag- und Trittkombinationen ohne Körperkontakt (Schattenboxen, Pratzen oder Sandsack) im Wechsel mit Fitness-Intervallen. Ausrüstung: Sportkleidung, Hallenschuhe, ggf. Boxhandschuhe und Handbandagen. Worauf achten: Schläge aus Hüfte und Rumpf führen, Ellbogen und Knie nicht überstrecken, Handgelenke gerade halten, Technik vor Tempo. Dauer: 45–60 Minuten.', 'Cardio', 'sonstige'),
  ('Kurs: HIIT / Tabata (Gruppenkurs)', 'Ganzkörper', 'Kursformat (Gruppen- oder Online-Kurs) – beim Loggen die tatsächliche Dauer in Minuten angeben. Ausführung: Hochintensives Intervalltraining in der Gruppe: kurze, intensive Belastungsphasen (z. B. 20 s) im Wechsel mit kurzen Pausen (z. B. 10 s) mit Eigengewichtsübungen. Ausrüstung: Matte, Hallenschuhe, Handtuch, Trinkflasche. Worauf achten: Vorher gründlich aufwärmen, Technik auch bei Ermüdung sauber halten, Intensität dem eigenen Niveau anpassen; bei Herz-Kreislauf-Erkrankungen oder Bluthochdruck vorab ärztliche Freigabe einholen. Dauer: 30–45 Minuten.', 'Bodyweight', 'sonstige'),
  ('Kurs: Bootcamp / Zirkeltraining', 'Ganzkörper', 'Kursformat (Gruppen- oder Online-Kurs) – beim Loggen die tatsächliche Dauer in Minuten angeben. Ausführung: Zirkelartiges Gruppentraining mit wechselnden Stationen (Eigengewicht, Kleingeräte, Lauf- und Sprungübungen) nach Zeit. Ausrüstung: Matte, Kleingeräte je nach Kurs, Hallen- oder Outdoor-Schuhe. Worauf achten: Übungen sauber statt schnell ausführen, Stationen dem eigenen Niveau anpassen, zwischen den Stationen ausreichend trinken. Dauer: 45–60 Minuten.', 'Bodyweight', 'sonstige'),
  ('Kurs: Bauch-Beine-Po (BBP)', 'Bauchmuskeln, Gesäß, Oberschenkel', 'Kursformat (Gruppen- oder Online-Kurs) – beim Loggen die tatsächliche Dauer in Minuten angeben. Ausführung: Gruppenkurs mit Kräftigungsübungen für Rumpf, Beine und Gesäß (Eigengewicht, teils mit Band oder Kleingerät). Ausrüstung: Matte, ggf. Widerstandsband oder Kleinhanteln. Worauf achten: Becken stabil, Knie in Fußrichtung, kein Hohlkreuz, Bauchspannung halten und ruhig weiteratmen. Dauer: 45–60 Minuten.', 'Bodyweight', 'sonstige'),
  ('Kurs: Bodypump (Langhantel-Gruppenkurs)', 'Ganzkörper', 'Kursformat (Gruppen- oder Online-Kurs) – beim Loggen die tatsächliche Dauer in Minuten angeben. Ausführung: Musikgeführtes Langhanteltraining in der Gruppe mit vielen Wiederholungen und moderaten Gewichten für alle großen Muskelgruppen. Ausrüstung: Langhantel mit Gewichtsscheiben, Step, Matte. Worauf achten: Gewicht so wählen, dass die Technik bis zum Ende sauber bleibt, Rücken gerade, Knie in Fußrichtung, bei Unsicherheit Technik von der Kursleitung prüfen lassen. Dauer: 45–60 Minuten.', 'Kraft', 'sonstige'),
  ('Kurs: Functional Training / Kettlebell', 'Ganzkörper', 'Kursformat (Gruppen- oder Online-Kurs) – beim Loggen die tatsächliche Dauer in Minuten angeben. Ausführung: Gruppentraining mit funktionellen Ganzkörperbewegungen (z. B. Kniebeugen, Schwünge, Tragen, Ziehen und Drücken) mit Kettlebell, Band oder Medizinball. Ausrüstung: Kettlebell, Widerstandsband, Medizinball, Matte. Worauf achten: Erst die Technik, dann das Gewicht; Rücken gerade, Rumpf angespannt, Schwünge aus der Hüfte statt aus dem Rücken. Dauer: 45–60 Minuten.', 'Kraft', 'sonstige'),
  ('Kurs: Kraftzirkel (Gerätezirkel)', 'Ganzkörper', 'Kursformat (Gruppen- oder Online-Kurs) – beim Loggen die tatsächliche Dauer in Minuten angeben. Ausführung: Betreutes Zirkeltraining an Kraftgeräten mit festen Zeiten je Station (z. B. 40 s Belastung, 20 s Wechsel) für Einsteiger und Fortgeschrittene. Ausrüstung: Kraftgeräte des Studios, Handtuch. Worauf achten: Sitz- und Gerätegeometrie vorab einstellen, Gewicht niedrig bis moderat wählen, Bewegungen kontrolliert und ohne Schwung ausführen. Dauer: 30–45 Minuten.', 'Kraft', 'sonstige')
)
insert into public.exercises (name, muscle_group, description, category, movement_pattern)
select d.name, d.muscle_group, d.description, d.category, d.movement_pattern
from data d
where not exists (select 1 from public.exercises e where e.name = d.name);
